### ISSUE TITLE
Modules support?

### ISSUE THREAD

**Issue by howesteve** [nhooyr/websocket#106]
Hello all,

Is there some issue with go modules? I have modules activated in a project, but when I try to install nhooyr/websocket, I get the following:

```
howe@hp /m/h/v/p/a/s/app> go get github.com/nhooyr/websocket
go: github.com/nhooyr/websocket@v1.3.1: parsing go.mod: unexpected module path "nhooyr.io/websocket"
go: error loading module requirements
```

My environment:
```
howe@hp /m/h/v/p/a/s/app> go version
go version go1.12.7 linux/amd64
howe@hp /m/h/v/p/a/s/app> echo $GO111MODULE
on
```

Thanks,
Howe

**Comment by nhooyr** [comment]
https://github.com/nhooyr/websocket#install

You want to run the following command:

```
go get nhooyr.io/websocket@v1.3.1
```

This library uses a custom import path so instead of `github.com/nhooyr/websocket`, its `nhooyr.io/websocket`.

**Comment by howesteve** [comment]
Hello @nhooyr ,

Thanks, I missed it. Using "nhooyr.io/websocket" on the go get command and on the .go source file had go.mod updated and everything worked.

Howe

**Comment by nhooyr** [comment]
Nice.
