### ISSUE TITLE
Weird behaviour when channelling go-capnproto2 over websocket

### ISSUE THREAD

**Issue by Vaelatern** [nhooyr/websocket#111]
My setup is a little convoluted. I use capnproto rpc over websockets (to simplify deployment) between my programs. However, the websocket server keeps failing to read a header somehow and crashes.

```
rpc: writing return: failed to write msg: websocket closed: failed to read header: EOF
```

and on the Dialer side:

```
rpc: writing finish: failed to write msg: context canceled
```

Sometimes both ends cancel their contexts at the same time. I'm not sure why.

**Comment by Vaelatern** [comment]
Turns out this happens when no headers are sent at all, I'm trying to send a header with my requests now to see if that changes something.

**Comment by nhooyr** [comment]
Hi I’m on vacation right now. I don’t have my laptop with me so I cannot help debug. I’ll be back in 2 weeksish and will look into this then. In the mean time def post anything you find.

I’m not sure why the lib sometimes sends no headers. Can you try using the default http client without any proxy or anything, just connect both sides over localhost and lmk if you can reproduce. It sounds like a bug in net/http.

**Comment by Vaelatern** [comment]
These are actually "net/http" and localhost already. I'm going to try adding debug prints to see exactly what the stack trace actually is.

**Comment by nhooyr** [comment]
Could you post a reproducible example if possible? Does this happen every time?

**Comment by Vaelatern** [comment]
Yes, every time. I'm trying to minimize the example as well.

**Comment by Vaelatern** [comment]
`{true false false false 2 48 true [184 234 196 219]}`

This is what readHeader() returns before the error shows up. I'm going to research more.

**Comment by Vaelatern** [comment]
https://gist.github.com/Vaelatern/dd8aae465e3807af5d189143377f5008 A minimum broken example.

**Comment by nhooyr** [comment]
Found it. The net conn wrapper needs to stop the timer if the time passed is the zero Value. Right now a zero value deadline cancels the ctx.

If you make a PR I’m happy to merge.

**Comment by Vaelatern** [comment]
Wonderful! I'll prepare a PR and have that in the next 12 hours. Thank you!

**Comment by Vaelatern** [comment]
It ever calls SetDeadline? I'll find out.

**Comment by Vaelatern** [comment]
SetDeadline is never called, this is weird.

**Comment by Vaelatern** [comment]
As I see it the NetConn wrapper stops the timer by default, never Reset()ing it again.

**Comment by Vaelatern** [comment]
Well, it defies explanation, but the patch works. I'll PR it.
