### ISSUE TITLE
Change options to be pointer structures

### ISSUE THREAD

**Issue by nhooyr** [nhooyr/websocket#122]
I feel like `websocket.AcceptOptions{}` and `websocket.DialOptions` is getting old.

I want to change the public API to accept pointers to the option structs and thus accept nil for the defaults. Nil at the end of a function is imo pretty clearly where some options structure goes. This is a relatively minor change so no major version change.

Does anyone have any strong opinions about this?

**Comment by nhooyr** [comment]
@cadler

**Comment by coadler** [comment]
I agree, would be nice to just pass nil instead of an empty struct every time.
