### ISSUE TITLE
Should websocket.NetConn take a context?

### ISSUE THREAD

**Issue by nhooyr** [nhooyr/websocket#125]
🤔 

Feels like it'd be nice to be able to cancel a context and guarantee that every open connection is over when using the NetConn adapter.

**Comment by nhooyr** [comment]
Any thoughts @coadler @jancona @Vaelatern

**Comment by Vaelatern** [comment]
I guess? It hasn't been important for me to be able to do this, and I'd have concerns about breaking an existing API.
