### ISSUE TITLE
Remove dependency on golang.org/x

### ISSUE THREAD

**Issue by nhooyr** [nhooyr/websocket#134]
See https://github.com/nhooyr/websocket/issues/128#issuecomment-527643088

Would be nice to be truly zero dep.

Right now we depend on httpguts and xerrors.

xerrors can be easily removed now that Go 1.13 is out. Only problem is no frame information anymore which is unfortunate but welp

For httpguts I think it can be easily removed too.

**Comment by andersfylling** [comment]
Will you be doing v2 release once this closes?

**Comment by nhooyr** [comment]
I'll release `v1.5.1`. I don't think we need to release a v2, `xerrors` and stdlib `errors` are fully compatible.

**Comment by coadler** [comment]
The frame information not making it into std is a big bummer.

**Comment by andersfylling** [comment]
You can actually use xerrors on go1.13 errors?

**Comment by nhooyr** [comment]
Yes, it's all based on interfaces so should just work.
