### ISSUE TITLE
Support disabling error writing via AcceptOptions

### ISSUE THREAD

**Issue by bontibon** [nhooyr/websocket#152]
By default, the library writes errors during the `websocket.Accept` call to the `http.ResponseWriter` (via `http.Error`).

It would be helpful if that feature could be disabled via an AcceptOptions field so that the caller can control how the error is returned to the user.

**Comment by nhooyr** [comment]
> It would be helpful if that feature could be disabled via an AcceptOptions field so that the caller can control how the error is returned to the user.

This was an explicit design choice since I couldn't reason when/why would this feature be required. What's your use case?

**Comment by bontibon** [comment]
I need to return a structured (e.g. JSON) response to the client if there is an error, where the current implementation only writes plain text.

**Comment by nhooyr** [comment]
> I need to return a structured (e.g. JSON) response to the client if there is an error, where the current implementation only writes plain text.

On the browser, WebSocket client's don't have access to the handshake response so in general, it won't do anything unless you *only* have Go clients.

If you still really want this, I'd recommend opting for a wrapper around http.ResponseWriter that converts error responses into JSON.

**Comment by nhooyr** [comment]
@bontibon Going to close this out since I believe the http.ResposneWriter wrapper enough as this is an uncommon use case. If you feel otherwise, please feel free to comment on this issue again and I'll reopen it.
