### ISSUE TITLE
CloseError wrapping

### ISSUE THREAD

**Issue by pymq** [nhooyr/websocket#161]
I think there is a misspelling: `%v` instead of `%w` [here](https://github.com/nhooyr/websocket/blob/5dca20e5d979ec57780356d722647163c7f91739/conn.go#L815).
My case is checking error from executing `conn.Read()` As `websocket.CloseError` and handle disconnection

**Comment by nhooyr** [comment]
So that's intended. See #103 

#160 should help clear this up and make it more intuitive.

The idea is that you only want to check for a status code you receive from the peer but if you send a status code, you don't want to check for it, just error out.
