### ISSUE TITLE
Return HTTP 426 status code when appropriate

### ISSUE THREAD

**Issue by nerg4l** [nhooyr/websocket#173]
At the moment during a handshake error the server will response with 400 status code for example:

```
HTTP/1.1 400 Bad Request
Content-Length: <content length>
Content-Type: text/plain; charset=utf-8

websocket protocol violation: Connection header "" does not contain Upgrade
```

However, wouldn't it be beneficial to respond with 426 status code when incorrect Connection/Upgrade header is given or the HTTP protocol of the request is bellow 1.1?

```
HTTP/1.1 426 Upgrade Required
Upgrade: WebSocket
Connection: Upgrade
Content-Length: <content length>
Content-Type: text/plain; charset=utf-8

websocket protocol violation: Connection header "" does not contain Upgrade
```

Also I would appreciate if there would be an option to disable the functionality of `Accept` which writes the error to the response and I could handle it "my way".

**Comment by nhooyr** [comment]
> However, wouldn't it be beneficial to respond with 426 status code when incorrect Connection/Upgrade header is given or the HTTP protocol of the request is bellow 1.1?

Yup, that's a bug, should be 426 there.

> Also I would appreciate if there would be an option to disable the functionality of Accept which writes the error to the response and I could handle it "my way".

See https://github.com/nhooyr/websocket/issues/152

It's not clear to me when it would be beneficial to disable the default error handling given its not application specific but if you must, you can wrap the http.ResponseWriter passed in.

**Comment by nerg4l** [comment]
> It's not clear to me when it would be beneficial to disable the default error handling given its not application specific but if you must, you can wrap the http.ResponseWriter passed in.

Thanks, I did not think about that one.
