### ISSUE TITLE
Add chat example

### ISSUE THREAD

**Issue by svycka** [nhooyr/websocket#174]
Hello @nhooyr,
maybe you could add chat example something like https://github.com/gorilla/websocket/tree/master/examples/chat would be easier to compare both implementations and also would serve as documentation.

**Comment by nhooyr** [comment]
> https://github.com/gorilla/websocket/tree/master/examples/chat would be easier to compare both implementations and also would serve as documentation.

I feel like the echo example covers the library well while still being light weight. The gorilla chat example is much more involved.

If you feel the echo example along with the comparison in the README does not suffice, then we can explore this.

**Comment by svycka** [comment]
I think chat example covers a lot more. And yes echo example shows basic usage quite well. But still something like chat example as this a common use case for websocket and easy to understand.

**Comment by nhooyr** [comment]
Fair enough.

**Comment by nhooyr** [comment]
My plan is to just remove the echo example and turn it into a full fledged chat example.

**Comment by svycka** [comment]
@nhooyr not sure why you want to remove it. Why it's bad keeping both? But if you think this way just remove it.

**Comment by GustavoCaso** [comment]
Hi!! 

For the past days, I have been working on a chat CLI written in go and using this WebSocket library. I'm not a very experience go developer, but I wanted to learn more and also use WebSockets which I haven't had the chance to do at my work.

I'm more than happy to go over my example and if it's good we can port it as documentation to the library.
Also, I'm happy to work on improving so any issue or PR is welcome.

Here is the repo https://github.com/GustavoCaso/go-chat-websockets

is missing a README and how to use it, but I plan on keep adding more logic into it. Also, I plan on writing a blog post to help other developers.

Congrats on the library @nhooyr 🎉

**Comment by izzymg** [comment]
I wrote a wrapper using nhooyr/websocket as well - [sockparty](https://github.com/izzymg/sockparty) which is very easy to turn into a chat with a few lines.

**Comment by nhooyr** [comment]
@GustavoCaso 

> I'm more than happy to go over my example, and if it's good, we can port it as documentation to the library.
> Is missing a README and how to use it, but I plan on keep adding more logic into it. Also, I plan on writing a blog post to help other developers.

That's awesome, please do.

I'll take care of this issue myself though soon as I have similar code already written. I'll add a link to your code and @izzymg's though in the README or wiki.

**Comment by nhooyr** [comment]
Added in https://github.com/nhooyr/websocket/pull/190

Needs docs but you can easily run with `go run .` in `example-chat` subdirectory and visit the URL printed.

**Comment by nerg4l** [comment]
@nhooyr In the current chat example you use a `/publish` endpoint that accepts `POST` requests to broadcast a message. Wouldn't it make sense to "publish" the messages on WebSocket instead of sending a request to an endpoint?

**Comment by nhooyr** [comment]
> @nhooyr In the current chat example you use a /publish endpoint that accepts POST requests to broadcast a message. Wouldn't it make sense to "publish" the messages on WebSocket instead of sending a request to an endpoint?

It would work as well but I made it an endpoint so you could publish messages via curl easily. Will document this decision better.

**Comment by nhooyr** [comment]
Fixed in #225
