### ISSUE TITLE
Misleading information about small code base while dependency to gorilla/websocket exists

### ISSUE THREAD

**Issue by falco467** [nhooyr/websocket#175]
The description cites a small code base of only 2200 lines as a benefit over gorilla/websocket. But gorilla/websocket is included as a dependency. So overall any bug in the bigger codebase of gorilla/websocket could also break this project. In the end the code of both projects (and several other indirect dependencies) needs to be tested and maintained for this project to work.

Possible Solutions would be to remove the dependency on gorilla/websocket, or to change the reade to reflect the dependency.

**Comment by nhooyr** [comment]
How is gorilla websocket included?

**Comment by coadler** [comment]
Gorilla is only used in [`frame_test.go`](https://github.com/nhooyr/websocket/blob/master/frame_test.go#L340) for benchmarking their `maskBytes` function. Unless you're running the `nhooyr/websocket` tests it won't be compiled.

**Comment by nhooyr** [comment]
Going to close since @coadler clarified.

**Comment by falco467** [comment]
You are absolutely right, it was my error -sorry.
Go doesn't make it quite that easy to get an overview over dependencies and which are used only for testing and which are used only for indirect tests. So it can take some time to verify runtime dependencies for all builds.

**Comment by nhooyr** [comment]
> Go doesn't make it quite that easy to get an overview over dependencies and which are used only for testing and which are used only for indirect tests. So it can take some time for a newcomer to verify runtime dependencies for all builds.

godoc has a nice page for this.

https://godoc.org/nhooyr.io/websocket?imports
