### ISSUE TITLE
Sec-WebSocket-Version missing from response on handshake error

### ISSUE THREAD

**Issue by nerg4l** [nhooyr/websocket#176]
RFC 6455 states the following in [Section 11.3.5. Sec-WebSocket-Version](https://tools.ietf.org/html/rfc6455#section-11.3.5):

>   The |Sec-WebSocket-Version| header field is used in the WebSocket
>   opening handshake.  It is sent from the client to the server to
>   indicate the protocol version of the connection.  This enables
>   servers to correctly interpret the opening handshake and subsequent
>   data being sent from the data, and close the connection if the server
>   cannot interpret that data in a safe manner.  **The |Sec-WebSocket-
>   Version| header field is also sent from the server to the client on
>   WebSocket handshake error, when the version received from the client
>   does not match a version understood by the server.  In such a case,
>   the header field includes the protocol version(s) supported by the
>   server.**

**Comment by nhooyr** [comment]
Nice catch, will fix.
