### ISSUE TITLE
How to emit with custom event name? and broadcast?

### ISSUE THREAD

**Issue by kabaluyot** [nhooyr/websocket#178]
Coming from socket.io background, its very hard to understand how this work using the "echo" example. I was able to find your library suitable for our application but the documentation makes you scratch your head especially for beginners like me. How to emit with custom event name? and broadcast?

**Comment by nhooyr** [comment]
This library is more low level than socket.io.

To emit events you write JSON to then connection with whatever structure you want and to broadcast events you need to keep track of the interested clients yourself.

I'd also recommend reading https://sookocheff.com/post/networking/how-do-websockets-work/ to understand how WebSockets work better.

**Comment by nhooyr** [comment]
You can also follow along on #174 for a more complete example.
