### ISSUE TITLE
Help with sessions and websockets

### ISSUE THREAD

**Issue by jherman** [nhooyr/websocket#181]
Hi y'all,

I'm attempting to use websockets with `github.com/alexedwards/scs` sessions. However even a simple application gives me a hijacked connection exception:

`http: response.WriteHeader on hijacked connection from github.com/alexedwards/scs.(*SessionManager).LoadAndSave.func1 (session.go:159)`

Apparently both websockets and sessions are trying to write headers? How do you alleviate this type of issue?

Thanks!

**Comment by nerg4l** [comment]
Hello @jherman ,

As far as I know once a connection is hijacked you can not write header. Once the upgrade happened the connection is different from a regular HTTP connection.

I would advise to to store state differently for WebSockets.

**Comment by jherman** [comment]
@nerg4l Thank you for the reply.

Perhaps I'm going about this wrong and you can enlighten me how I should go about this.  Right now a user can issue a command via the UI  via an API call. The server processes the command and is suppose to inform the user it's been completed via websockets.  Well there can be several users logged in at once, so I don't want User A seeing User B's actions. So my thought was to create and manage hubs using session id's tied to the user. This way I can see what session id issued a command, and can just use the websocket associated with that session id, to indicate back to the user their command was completed.

Could you elobrate on storing state differently for websockets?

**Comment by coadler** [comment]
The only real ways to do user identification with websockets are with a query param or by sending an identify payload as the clients first message.

**Comment by nhooyr** [comment]
WebSockets take over the HTTP connection so you can’t do anything http related after the connection is established. You can’t use that library with WebSockets, you’ll need to handle sessions yourself.
