### ISSUE TITLE
Make library compatible with go1.12

### ISSUE THREAD

**Issue by ivansamsonov** [nhooyr/websocket#182]
Hello! I think it would be nice to support go1.12 as well, since 1.13 is a "too fresh" version. Currently I can't use this library since my company is using go1.12

**Comment by nhooyr** [comment]
Sure will do, should be fairly easy given the only thing we rely on is the new features in package errors.

**Comment by nhooyr** [comment]
After #163 since its a large refactor.

**Comment by nhooyr** [comment]
Done in #163

**Comment by nhooyr** [comment]
Just tested and does not work yet, I was using a bunch of Go 1.13 features without realizing it. Will test before closing.

**Comment by nhooyr** [comment]
Unfortunately Go 1.12 would break Wasm support :(

I'd recommend using https://github.com/nhooyr/websocket/tree/v1.5.0 if you need Go 1.12 support as that's the last release without Wasm.

This issue was also opened several months ago so hopefully you've been able to move to Go 1.13 anyway.
