### ISSUE TITLE
gRPC over WS and WASM

### ISSUE THREAD

**Issue by thegrumpylion** [nhooyr/websocket#183]
Hi there! Nice project.

I would like to have fully functional gRPC from the browser and the best way to go about it at the moment, as far as i can tell, is with websockets.

So i've used this library to see how far i can go and with very little code i made it work. Here's the result: https://github.com/thegrumpylion/grpcws

Is this functionality something that this library is interested in providing?

If so, the implementation, though works, feels a bit hackish. Maybe there's a better way to achieve this if it becomes part of this library?

Love to here your thoughts.

**Comment by thegrumpylion** [comment]
Also, since `HTTPClient` is not supported in `DialOptions` does that mean there is no way for me to secure the channel?

**Comment by nhooyr** [comment]
That's really cool but I would consider it out of scope for this library, especially considering there is a competing grpc-web spec. See https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md#protocol-differences-vs-grpc-over-http2

I think grpc-go would be better place for something like this.

> Also, since HTTPClient is not supported in DialOptions does that mean there is no way for me to secure the channel?

You want to use HTTPS to secure the WebSocket.
