### ISSUE TITLE
DisableKeepAlives in transport causes failure

### ISSUE THREAD

**Issue by jefferai** [nhooyr/websocket#185]
This appears at first blush to be similar-ish to #67 

If you are setting a custom http.Client (e.g. using https://github.com/hashicorp/go-cleanhttp), if the transport used in the client has keepalives disabled (that is, `DisableKeepAlives = true`), the connection will fail with

> failed to websocket dial: websocket protocol violation: Connection header "" does not contain Upgrade

This might be worth mentioning/detecting.

**Comment by nhooyr** [comment]
This is a bug in net/http. With DisableKeepAlives enabled, net/http writes a `Connection: close` header even if we already wrote a `Connection: Upgrade` header. Thanks for the report, I'll file a bug there.

**Comment by nhooyr** [comment]
Nvm sorry the problem is that net/http doesn't allow writing a Connection header if the request contains `Connection: close`.

**Comment by nhooyr** [comment]
https://github.com/golang/go/issues/36381
