### ISSUE TITLE
Pinging not working as expected

### ISSUE THREAD

**Issue by pmwebster** [nhooyr/websocket#186]
It's very possible I'm using this wrong, but pulling from your echo example, and your tests, a simple ping test with the following fails:
```go
package main

import (
	"context"
	"fmt"
	"log"
	"net"
	"net/http"
	"time"

	"nhooyr.io/websocket"
	"nhooyr.io/websocket/wsjson"
)

func main() {
	l, err := net.Listen("tcp", "localhost:0")
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	defer l.Close()

	s := &http.Server{
		Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			err := pingServer(w, r)
			if err != nil {
				log.Printf("echo server: %v", err)
			}
		}),
		ReadTimeout:  time.Second * 15,
		WriteTimeout: time.Second * 15,
	}
	defer s.Close()

	go func() {
		err := s.Serve(l)
		if err != http.ErrServerClosed {
			log.Fatalf("failed to listen and serve: %v", err)
		}
	}()

	err = client("ws://" + l.Addr().String())
	if err != nil {
		log.Fatalf("client failed: %v", err)
	}
}

func pingServer(w http.ResponseWriter, r *http.Request) error {
	c, err := websocket.Accept(w, r, nil)
	if err != nil {
		return err
	}
	defer c.Close(websocket.StatusInternalError, "the sky is falling")

	log.Println("Pinging client")
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*5)
	defer cancel()

	err = c.Ping(ctx)
	if err != nil {
		return err
	}
	return nil
}

func pong(ctx context.Context, c *websocket.Conn) {
	ctx, cancel := context.WithTimeout(ctx, time.Second*10)
	defer cancel()
}

func client(url string) error {
	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
	defer cancel()

	c, _, err := websocket.Dial(ctx, url, nil)
	if err != nil {
		return err
	}
	defer c.Close(websocket.StatusInternalError, "the sky is falling")

	for {
		v := map[string]int{}
		err = wsjson.Read(ctx, c, &v)
		if err != nil {
			return err
		}

		fmt.Printf("received: %v\n", v)
	}

	c.Close(websocket.StatusNormalClosure, "")
	return nil
}

```

Output:
```
2020/02/10 22:09:42 Pinging client
2020/02/10 22:09:47 echo server: failed to ping: failed to wait for pong: context deadline exceeded
2020/02/10 22:09:47 client failed: failed to read json: failed to get reader: failed to read frame header: read tcp 127.0.0.1:51279->127.0.0.1:51278: read: connection reset by peer
exit status 1
```
Is there a different way this is supposed to be used? Thanks for any insight!

**Comment by nhooyr** [comment]
So you send a ping but because you are never reading in the server goroutine, the pong is never read.

See the docs on the Ping method.

**Comment by nhooyr** [comment]
https://godoc.org/nhooyr.io/websocket#Conn.Ping

**Comment by nhooyr** [comment]
If you explicitly want to ignore messages, use `c.CloseRead` and then your example will work.

**Comment by nhooyr** [comment]
```go
package main

import (
	"context"
	"fmt"
	"log"
	"net"
	"net/http"
	"time"

	"nhooyr.io/websocket"
	"nhooyr.io/websocket/wsjson"
)

func main() {
	l, err := net.Listen("tcp", "localhost:0")
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	defer l.Close()

	s := &http.Server{
		Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			err := pingServer(w, r)
			if err != nil {
				log.Printf("echo server: %v", err)
			}
		}),
		ReadTimeout:  time.Second * 15,
		WriteTimeout: time.Second * 15,
	}
	defer s.Close()

	go func() {
		err := s.Serve(l)
		if err != http.ErrServerClosed {
			log.Fatalf("failed to listen and serve: %v", err)
		}
	}()

	err = client("ws://" + l.Addr().String())
	if err != nil {
		log.Fatalf("client failed: %v", err)
	}
}

func pingServer(w http.ResponseWriter, r *http.Request) error {
	c, err := websocket.Accept(w, r, nil)
	if err != nil {
		return err
	}
	defer c.Close(websocket.StatusInternalError, "the sky is falling")

	log.Println("Pinging client")
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*5)
	defer cancel()

	ctx = c.CloseRead(ctx)

	err = c.Ping(ctx)
	if err != nil {
		return err
	}
	return nil
}

func pong(ctx context.Context, c *websocket.Conn) {
	ctx, cancel := context.WithTimeout(ctx, time.Second*10)
	defer cancel()
}

func client(url string) error {
	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
	defer cancel()

	c, _, err := websocket.Dial(ctx, url, nil)
	if err != nil {
		return err
	}
	defer c.Close(websocket.StatusInternalError, "the sky is falling")

	for {
		v := map[string]int{}
		err = wsjson.Read(ctx, c, &v)
		if err != nil {
			return err
		}

		fmt.Printf("received: %v\n", v)
	}

	c.Close(websocket.StatusNormalClosure, "")
	return nil
}
```

This succeeds with:

```
$ go run main.go
2020/02/10 23:19:38 Pinging client
2020/02/10 23:19:38 client failed: failed to read json: failed to get reader: failed to read frame header: EOF
```

Now only the client fails.

**Comment by pmwebster** [comment]
Thanks for clarifying that! The docs make perfect sense now. Cheers!

**Comment by guille50** [comment]
I'm not sure if did it wright but because I have spend around a day trying to make work the ping functionality I'm leaving an example how I'm using it



`package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"time"

	uuid "github.com/satori/go.uuid"
	"nhooyr.io/websocket"
	"nhooyr.io/websocket/wsjson"
)

func startWSserver(connectionList map[string]*websocket.Conn) {
	fn := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Println(connectionList)

		c, err := websocket.Accept(w, r, &websocket.AcceptOptions{
			Subprotocols: []string{},
		})
		fmt.Println(c.Subprotocol())
		if err != nil {
			log.Println("ss", err)
			return
		}
		defer c.Close(websocket.StatusInternalError, "Session closed by the server")

		u1 := uuid.NewV4()
		connectionList[u1.String()] = c

		ctx, cancel := context.WithCancel(context.Background())
		defer cancel()

		// go Ping(c)
		t := time.NewTicker(time.Second * 2)
		defer t.Stop()

		for {
			select {
			case <-ctx.Done():
				c.Close(websocket.StatusNormalClosure, "")
				return
			case <-t.C:
				err = wsjson.Write(ctx, c, "hi")
				if err != nil {
					log.Println(err)
					return
				}
			}
		}
	})
	go http.ListenAndServe("10.10.40.25:4123", fn)

}

// Ping is
func Ping(c *websocket.Conn, agent string, sessionList map[string]*websocket.Conn) {

	go func() {
		ctxRead := context.Background()
		c.CloseRead(ctxRead)
	}()

	go func() {
		ctxPing, cancel := context.WithTimeout(context.Background(), time.Second*10)
		defer cancel()
		pingErr := c.Ping(ctxPing)
		if pingErr == nil {
			fmt.Println("Pinged client")

		} else {
			fmt.Println("Failed to ping client")
			fmt.Println(pingErr)
			fmt.Println("removing session")
			delete(sessionList, agent)

		}
	}()
	time.Sleep(time.Second * 5)
}

func main() {
	connectionList := map[string]*websocket.Conn{}
	startWSserver(connectionList)

	for {
		for key, conn := range connectionList {
			fmt.Println("->before ping")
			Ping(conn, key, connectionList)
			fmt.Println("->after ping ")
		}
		time.Sleep(time.Second * 5)
	}
}
`

If anyone want to try it, just replace the address of the Web server. 
In my scenario I need to keep the socket connection as far the client still connected and I the client that I'm going to write would not send any data but pong to the server
