### ISSUE TITLE
Strange problem with Firefox

### ISSUE THREAD

**Issue by gandaldf** [nhooyr/websocket#189]
Hi I'm trying to build a simple demo with an HTML page that sends message to the server and it returns them back to the page, but I have a strange problem in Firefox (73).
When I try to connect to my page, Firefox immediately closes the connection, an error appears in the console like:
`Firefox cannot establish a connection with the server "ws://localhost:7070/echo."`
In my Golang debug window I get:
`failed to accept WebSocket connection: WebSocket protocol violation: Connection header "keep-alive, Upgrade" does not contain Upgrade`
I have no problem with Chrome; can you help me with this bug?

**Comment by nhooyr** [comment]
Confirmed, bug in the accept code.

Just pushed a commit to fix and tagged the new release v1.8.2.

Thanks for reporting!
