### ISSUE TITLE
Seeing failed to get reader and to write msg errors

### ISSUE THREAD

**Issue by gandaldf** [nhooyr/websocket#191]
Hi, I just updated your library to the last version; I tried a basic example with two Websocket connection and get these errors in my Go debug console:

`failed to get reader: received close frame: status = StatusGoingAway and reason = ""`
on page load (when HTML page try to open the Websocket connection).

and:

`write: failed to write msg: failed to close writer: failed to write fin frame: failed to flush: write tcp 127.0.0.1:7070->127.0.0.1:61615: write: broken pipe`
on writing (when my Go code try to send a message to the HTML page).

These errors pop out with Firefox (73) and Chrome (79), but I think they are mostly "warnings" because everything seems to work.
Anyway, I never had these errors in older versions of your library and my frontend code is still the same.
Can you investigate, please?

**Comment by nhooyr** [comment]
StatusGoingAway means the WebSocket was closed by the browser as the window was closed.

The second error means a Write was in progress when the connection was closed.

Both seem normal to me.

**Comment by nhooyr** [comment]
I'd recommend ignoring read/write errors as there's really nothing you can do and they're unlikely to be useful in debugging.

**Comment by nhooyr** [comment]
It is definitely bizarre that you only get these errors with the latest version though.

If you downgrade, what happens?

**Comment by nhooyr** [comment]
Also what version were you on last?

**Comment by nhooyr** [comment]
Feel free to reopen if you have any further issues.

**Comment by nhooyr** [comment]
Another user has reported this, fixing. @coadler
