### ISSUE TITLE
Is subprotocols field required in header?

### ISSUE THREAD

**Issue by liminghuang** [nhooyr/websocket#196]
I used customize http client and header included 'Sec-WebSocket-Protocol' like below

```
opt := websocket.DialOptions{}

req := make(http.Header)
req["Origin"] = []string{"http://test.origin.com"}
req["cache-control"] = []string{"no-cache"}
req["Sec-WebSocket-Extensions"] = []string{}
req["Sec-WebSocket-Protocol"] = []string{"my-protocol"}
... ... ... 
... ... ...
transport := &http.Transport{TLSClientConfig: tlsC}
client := &http.Client{Transport: transport}

opt.HTTPHeader = req
opt.HTTPClient = client
```
The WSS connection will be fail because of verifySubprotocol function as below.

dial.go, line 204
```
err := verifySubprotocol(opts.Subprotocols, resp)
if err != nil {
    return nil, err
}
```

I traced the flow and found that library compared  "Sec-WebSocket-Protocol" with Subprotocols in http client header. So, I added a field in my http client header as below
```
opt.Subprotocols = []string{"my-protocol"}
```
At this time, the WSS server(written by node.js) rejected my WSS request.

If Sec-WebSocket-Protocol is needed to compare with subprotocols, does the subprotocols field need to exist in http client or not?
I disable the verifySubprotocol check and the WSS server accept the request. 

This go library cancel the WSS request when I missed Subprotocols field.
The node.js WSS server reject request when I added Subprotocols field in http header.
I'm confuse what library is correct. 

thanks

**Comment by liminghuang** [comment]
By the way, I use gorilla WSS lib with same http header to connect node.js server is fine.

**Comment by nhooyr** [comment]
You only need to set `opts.Subprotocols` and then things should just work.

You don't need

```
req["Sec-WebSocket-Extensions"] = []string{}
req["Sec-WebSocket-Protocol"] = []string{"my-protocol"}
```

Was there any error from the nodejs server when it rejected your connections?

**Comment by liminghuang** [comment]
@nhooyr 
Thanks a lot, I removed the ```req["Sec-WebSocket-Protocol"]``` and set set ```opts.Subprotocols``` only, it's fine now! But why?
I read the RFC doc, Sec-WebSocket-Protocol is a list of values indicating which protocols the client would like to speak.
It looks like 'req["Sec-WebSocket-Protocol"]' has to exist in header.

**Comment by nhooyr** [comment]
Hmm not sure why that fixed anything. The header gets overridden anyway in dial.go in handshakeRequest. Glad it’s fixed.
