### ISSUE TITLE
Demo Do not understand

### ISSUE THREAD

**Issue by lubaoyilang** [nhooyr/websocket#203]
Your example demo Force display of all APIs

but To really be a WS server, you need to time out, you need to save Conn。。。

Is it possible to have a practical Demo？

**Comment by nhooyr** [comment]
Sorry I don't understand what you mean. Could you elaborate?

**Comment by lubaoyilang** [comment]
Need more real examples
Group chat，storage Conn、Read everyone message

**Comment by nhooyr** [comment]
https://github.com/nhooyr/websocket/tree/master/chat-example
