### ISSUE TITLE
godoc.org shouldn't be updated before the release

### ISSUE THREAD

**Issue by aidin-gh** [nhooyr/websocket#206]
I was trying to run the [Echo Example](https://godoc.org/nhooyr.io/websocket#example-package--Echo), and I couldn't compile it because of `websocket.Grace is undefined` error. It took me quite sometime to figure out what's happening.

`Grace` only added recently. The `go mod` fetches the latest release, which doesn't have the `Grace`.

It can be very confusing to see some structs/funcs in the docs that aren't released yet. Or maybe, signature changes.

**Comment by nhooyr** [comment]
Unfortunately, godoc always uses the default branch. I suppose I could default the repo to a release branch to avoid troubles.

**Comment by nhooyr** [comment]
Fixed, thanks for reporting.
