### ISSUE TITLE
Example codes in the documents must be complete

### ISSUE THREAD

**Issue by aidin-gh** [nhooyr/websocket#207]
For example, in the Echo Example, `echoServer` and `client` functions aren't defined. It's not obvious how one should define them.

Also, it seems like a good idea to have an `example` directory in the source tree with all the examples in it. So, instead of having to copy and paste from docs, examples are just there next to the source code someone downloaded, and can be compile and run. Or, they can be explored right through the Github's Web UI.

**Comment by nhooyr** [comment]
Examples are here:

1. https://github.com/nhooyr/websocket/blob/master/example_echo_test.go
1. https://github.com/nhooyr/websocket/blob/master/example_test.go

Yea I see what you mean, seems to be a new godoc bug.

**Comment by nhooyr** [comment]
Mhmm yea if you run `godoc -http=:8085` locally then the example shows up properly 😕

**Comment by nhooyr** [comment]
Reported to the go team, turns out full file examples don't show up correctly if you only have functions. Adding a type fixed it in my test repo https://github.com/nhooyr/websocket3

cc @julieqiu

**Comment by nhooyr** [comment]
I'll clarify the docs in the meantime that the examples can be found on GitHub.

**Comment by aidin-gh** [comment]
Awesome. Thanks.
