### ISSUE TITLE
Disable permessage-deflate compression extension via build tag

### ISSUE THREAD

**Issue by zhangyoufu** [nhooyr/websocket#211]
I wish I could disable this feature via build tag (and eliminate dependency on `github.com/klauspost/compress`)

**Comment by nhooyr** [comment]
I agree that'd be useful but I'm not convinced its worth the complexity of a build tag. Have you measured how much binary bloat it causes?

**Comment by zhangyoufu** [comment]
> I'm not convinced its worth the complexity of a build tag

In my limited Golang experience, decoupling extensions/modules with build tags may help separating things in a more clear manner. Just a wish.

> Have you measured how much binary bloat it causes?

Nope.

**Comment by nhooyr** [comment]
While it can help, it bloats the codebase with many extra files. So for now I think it's best to avoid this route. I don't think the extra package will be a deterrent for 99.99% of use cases and ideally the stdlib would catch up to klauspost/compress and we can move off it at some point.
