### ISSUE TITLE
Outdated documentation re close handshake timeout

### ISSUE THREAD

**Issue by zhangyoufu** [nhooyr/websocket#212]
https://github.com/nhooyr/websocket/blob/ff876f6d14d96bf1de6094887d6bbf167991b046/close_notjs.go#L18-L19

https://github.com/nhooyr/websocket/blob/ff876f6d14d96bf1de6094887d6bbf167991b046/close_notjs.go#L83-L87

Conn.Close may block for up to 5s (stuck in writeControl due to congestion control, w/o triggering timeout) + 10s (wait peer).

**Comment by nhooyr** [comment]
Nice catch, will fix soon.
