### ISSUE TITLE
make nhooyr.io/websocket/internal/test/wstest public

### ISSUE THREAD

**Issue by zhangyoufu** [nhooyr/websocket#214]
This package is useful for anyone writing WebSocket-related test cases. But it is an internal package, thus cannot be used outside `nhooyr.io/websocket`.

I think this package should be moved out of internal, like the relationship between `net/http` and `net/http/httptest`.

**Comment by zhangyoufu** [comment]
duplicate of #197

**Comment by nhooyr** [comment]
Yea, definitely a very useful package, happy there's demand for it :) will def close out #197 sooner.
