### ISSUE TITLE
Write doesn't check if connection is closed before returning error

### ISSUE THREAD

**Issue by zhangyoufu** [nhooyr/websocket#215]
If Conn.Close is called when there's on-going read/write, read/write may return I/O error instead of wrapping a CloseError, and there is no trivial way to examine whether this I/O error is caused by calling Conn.Close.

Of course I can record the code and reason before I call Conn.Close, but there is still a race between my call to Conn.Close and something like WebSocket protocol error. My recorded code and reason may not reflect what actually sent to remote peer in the close frame.

# How to reproduce
```go
package main

import (
	"context"
	"log"
	"time"

	"nhooyr.io/websocket"
)

func work(ctx context.Context) (err error) {
	client, _, err := websocket.Dial(ctx, "ws://demos.kaazing.com/echo", nil)
	if err != nil { return }
	log.Print("connected")

	// write something in background
	errCh := make(chan error)
	go func() {
		for {
			err := client.Write(ctx, websocket.MessageText, []byte("hello"))
			if err != nil {
				errCh <- err
				return
			}
			time.Sleep(50 * time.Millisecond)
		}
	}()

	// close after some time
	time.Sleep(3 * time.Second)
	log.Print("closing")
	err = client.Close(websocket.StatusNormalClosure, "bye")
	if err != nil { return err }
	log.Print("closed")

	return <-errCh
}

func main() {
	err := work(context.Background())
	if err != nil && websocket.CloseStatus(err) != websocket.StatusNormalClosure {
		log.Fatal(err)
	}
}
```

# Expected output
```
2020/03/15 14:14:00 connected
2020/03/15 14:14:03 closing
2020/03/15 14:14:03 closed
```

# Actual output (sometimes, due to race)
```
2020/03/15 14:13:54 connected
2020/03/15 14:13:57 closing
2020/03/15 14:13:58 failed to close WebSocket: failed to read frame header: read tcp 192.168.1.2:57362->34.209.17.111:80: read: connection reset by peer
```

**Comment by nhooyr** [comment]
Is your echo server written with this library?

The error indicates the library did not receive a close frame from the peer.

**Comment by nhooyr** [comment]
Will note that I should add an error wrap in https://github.com/nhooyr/websocket/blob/ff876f6d14d96bf1de6094887d6bbf167991b046/close_notjs.go#L83 to make that clear.

**Comment by zhangyoufu** [comment]
> Is your echo server written with this library?

The echo server used is hosted by 3rd party. (It has some strange behavior on continuation frame, but not related to this issue.)

> The error indicates the library did not receive a close frame from the peer.

These I/O errors are actually caused by underlying socket being closed. In such case, I expect any in-progress Read/Reader/Write/Writer return the CloseError that triggered WebSocket closing, instead of return an I/O error like `read: connection reset by peer`. This is a race between read/write and close.

**Comment by zhangyoufu** [comment]
The code I provided does not show the problem clearly. I'm going to close this issue and open another.

**Comment by nhooyr** [comment]
All in progress reads and writes will do what you describe. But the close itself will return an IO error if it occurred as that means the close handshake wasn’t done.

**Comment by nhooyr** [comment]
Nvm it looks like I missed this on writes when I recently refactored the library. Thanks for reporting will fix soon.
