### ISSUE TITLE
klauspost/compress is 21 megabytes

### ISSUE THREAD

**Issue by nhooyr** [nhooyr/websocket#220]
Some user's reported an issue with the dependency being large https://github.com/diamondburned/arikawa/issues/11

I confirmed, the dependency is 21 megabytes.

I think the best approach would be to vendor only the code we need from klauspost/compress.

cc @klauspost

**Comment by diamondburned** [comment]
Seeing how the `compress` PR used [github.com/klauspost/compress/flate](https://godoc.org/github.com/klauspost/compress/flate), can the stdlib [compress/flate](https://golang.org/pkg/compress/flate/) be used instead?

**Comment by nhooyr** [comment]
stdlib compress/flate is significantly slower. See https://github.com/klauspost/compress/pull/216#issuecomment-586638251

**Comment by nhooyr** [comment]
And allocates much more memory.

**Comment by diamondburned** [comment]
I think 2x slower isn't that big of a deal. If anything, the library can also allow an interface to give developers choices when it comes to performance-intensive tasks.

**Comment by diamondburned** [comment]
Alternatively, I think @klauspost should really split up his repositories. Seeing how the largest file seems to be from `compress/zstd`, he could probably split 5 of his subpackages into 5 repositories.

![image](https://user-images.githubusercontent.com/8463786/78310908-2b009980-7504-11ea-90b8-ec314907194c.png)

**Comment by pollen5** [comment]
Vendoring only needed code sounds good.

**Comment by klauspost** [comment]
No. If 21 megs is a problem for you, do what you want.

**Comment by nhooyr** [comment]
> The question is why is he pushing test data to the repo.

Everyone pushes tests to repos.

Like @klauspost said, I'm not entirely sure this is a problem worth solving.

**Comment by nhooyr** [comment]
I think the default should use stdlib and then I can maintain a separate branch if there's enough interest until/if stateless compression ends up in the stdlib. It's always nice to have zero dependencies as well.
