### ISSUE TITLE
wsjson failed to acquire lock

### ISSUE THREAD

**Issue by Iron-E** [nhooyr/websocket#221]
# Context

I am creating a simple [chat application](https://gitlab.com/networking-final/chat-server) using this library. I have created a [client](https://gitlab.com/networking-final/chat-client) to go along with it.

It seems that there is a bug somewhere either in my usage of or in the `wsjson` library, specifically in [this](https://gitlab.com/networking-final/chat-server/-/blob/master/internal/net/ws/handlers/chat/handle.go) file.

# Description

Whenever two clients are connected to the server at the same time, I get the following error message (from my `zap` logger, see the `"error"` field):

```json
"level": "error",
"caller": "chat/handle.go:114",
"Function": "NewChatHandlerFunc()",
"error": "failed to read JSON message: failed to get reader: WebSocket closed: failed to acquire lock: context deadline exceeded",
```

I can't find anything about the source of this error, except the file that it originates in is [wsjson/wsjson.go](https://github.com/nhooyr/websocket/blob/master/wsjson/wsjson.go). 

# Observations

* In my application, there is only one place that messages are read from. Similarly, there is only one place where they are written.
* I use the `context.Background()` for my one and only `wsjson.Read()` call, so how could it be failing with a "deadline exceeded" message? What deadline could it be referring to?
* I use a `context.WithTimeout(context.Background(), 10 * time.Second)` for my `wsjson.Write()` calls, but my clients disconnect _much_ faster than 10 seconds (they disconnect immediately). 

# Other notes

I have read the chat and ping examples, and that is where the general structure of the file that I linked to came from.

**Comment by nhooyr** [comment]
So it says the WebSocket was closed because a context was cancelled on some other operation, most likely a write.

**Comment by nhooyr** [comment]
I think this is a good place to be more clear about the error message, we should indicate what type of lock is being waited on.

**Comment by nhooyr** [comment]
Most likely, this is due to a concurrent write taking too long.

**Comment by nhooyr** [comment]
To be clear, it's unlikely to be a bug in the library since there's now a concurrency test for the library where 10 clients blast the chat example with 128 messages of 128 bytes concurrently and the test ensures all messages are received.

See https://github.com/nhooyr/websocket/blob/dev/chat-example/chat_test.go#L53

**Comment by Iron-E** [comment]
I looked at the example, and one thing in particular is puzzled me after.  Here is a snippet from [conn_notjs.go](https://github.com/nhooyr/websocket/blob/master/conn_notjs.go), lines 241–244:

```go
case <-ctx.Done():
	err := fmt.Errorf("failed to acquire lock: %w", ctx.Err())
	m.c.close(err)
	return err
```

This is the case that is generating the error that I am seeing. However, here is the context that I am using:

```go
ctx, cancel := context.WithTimeout(
	context.Background(), 10 * time.Second,
)
```

If I am understanding things correctly (I have done most of my work in Dart, I'm new to Go), then `ctx.Done()` should return after 10 seconds. However, it was returning immediately (and I even tested this to affirm it). So at this point, I knew it was not this library, but the `context` library that was exhibiting the behaviour that led to this error.

In the examples, a `context` is generated outside of the `for {}` loop that listens for events. However, in this case, that was the exact cause of the error: as soon as I switched to generating a context each time I needed to send a message, and then immediately discarding it, the errors were gone and everything is working as intended.

I wasn't under the impression that `context`s behave that way. Is that supposed to happen? The way that my code ended up working is different than the [echo example demonstrates](https://godoc.org/nhooyr.io/websocket#ex-package--Echo):

```go
ctx, cancel := context.WithTimeout(r.Context(), time.Minute*10)
defer cancel()

…

for {
	…
	select {
	case <-t.C:
		wsjson.Write(ctx, c, "hi")
	}
}
```

To relate my code back to the example, what ended up working looked like this:

```go
…
for {
	…
	select {
	case <-t.C:
		ctx, cancel := context.WithTimeout(r.Context(), time.Minute*10)
		wsjson.Write(ctx, c, "hi")
		cancel()
	}
}
```

**Comment by nhooyr** [comment]
Ah I understand the confusion.

The echo example does create a new context for every read/write, it doesn't reuse.

See https://github.com/nhooyr/websocket/blob/66eb672e854683f7295d1c068b1d725acba4beca/example_echo_test.go#L100

> Thanks for helping me figure this out, by the way. You really helped me out.

No problem :)
