### ISSUE TITLE
SetDeadline should only close the connection if there is an in progress Read/Write

### ISSUE THREAD

**Issue by emersion** [nhooyr/websocket#228]
I'm using `websocket.NetConn`. `net.Conn` docs say:

>A deadline is an absolute time after which I/O operations fail with a timeout (see type Error) instead of blocking.

However this closes the connection 10s after the write, even if the write has already completed:

```
conn.SetWriteDeadline(time.Now().Add(10 * time.Second)
conn.Write([]byte("hello world"))
```

**Comment by nhooyr** [comment]
This is documented on `websocket.NetConn`.

Unfortunately nothing can be done about it as closing the connection is the only way to unblock any reading/writing goroutines as this library treats the underlying connection as `io.ReadWriteCloser` even if it's a net.Conn.

The reasoning behind this is that net/http's Client only gives us back a `io.ReadWriteCloser` for HTTP upgrades.

Another reason is that when http2 upgrades are supported, we'd also only have access to a `io.ReadWriteCloser` on both the client and server.

So while on the server we could theoretically access the SetDeadline methods on the net.Conn for HTTP/1, it's best not to depend on them at all.

**Comment by nhooyr** [comment]
Actually I see your point, we could only close the connection if there is an in progress read/write but otherwise we don't have to.
