### ISSUE TITLE
fasthttp/fiber support?

### ISSUE THREAD

**Issue by khaibin** [nhooyr/websocket#229]
Hi, I would like to use the websocket with https://github.com/gofiber/fiber

any plans for fasthttp support? thanks!

**Comment by nhooyr** [comment]
I don't think there should be anything added here for support.

I'd recommend opening an issue on fasthttp to add support for `http.Hijacker` so that you can pass it in and easily use this library.

**Comment by nhooyr** [comment]
For now you can implement it yourself with `https://godoc.org/github.com/valyala/fasthttp#RequestCtx.Hijack`
