### ISSUE TITLE
Problem dialing in WASM

### ISSUE THREAD

**Issue by kyeett** [nhooyr/websocket#232]
Hi!

First of all, thank you for a nice library.

I'm developing a small 2D game (https://kyeett.github.io/adventure/), and try to implement multiplayer using `nhooyr/websocket`. 
1. This works great if run the code on my desktop (`go run *.go`)
2. When I compile it to WASM. It seems to just get stuck at the dial step.

```
c, _, err := websocket.Dial(ctx, u.String(), nil)
if err != nil {
	log.Fatal("dial:", err)
}
```

Symptoms
* CPU of browser is 100% (tested in Chrome and Safari)
* Browser tab cannot be closed 
* Server side logs show that the client has connected (I have a WS server using https://github.com/olahol/melody)
 
If you have any ideas of how to troubleshoot this, or what could be the problem, I would be grateful.

My code is here, if it is useful:
* https://github.com/kyeett/adventure/blob/01c6f7f528da42dc4f8345bbb711c5549a77e531/internal/network/network.go#L39

**Comment by kyeett** [comment]
Callstack
![image](https://user-images.githubusercontent.com/737646/81008532-62d86500-8e53-11ea-90e0-be55f8066c0b.png)

**Comment by nhooyr** [comment]
Weird. I'd recommend adding a timeout to the dial, it may help to see if the code is blocked due to a bug or waiting on the network for some reason.

**Comment by nhooyr** [comment]
Does the callstack never change? It's stuck at js.valueNew?

**Comment by kyeett** [comment]
Hi!

Thank you for a quick response. I managed to create a minimal working example, where everything works as expected! 

I think I can continue troubleshooting and figure out what is the difference between the minimal example, and my game.

I can report back here if I find something useful.

**Comment by nhooyr** [comment]
Sounds good.

**Comment by colek319** [comment]
@kyeett I'm having this same issue. What was the problem?

**Comment by kyeett** [comment]
@colek319, I don't remember, I'm afraid. 

I managed to dig up the commit from my repo that claims it fixed something with wasm and websockets, but I don't know how 😄 .

https://github.com/kyeett/adventure/commit/dc4d19281a19b64a9cf2b2a2a91ee9381365229a

There are a few things that I see in the code that might have fixed it, or helped to troubleshoot:
* Don't `log.Fatal` deep in the code. Handle gracefully and log somehow 
  * https://github.com/kyeett/adventure/commit/dc4d19281a19b64a9cf2b2a2a91ee9381365229a#r48240327
* Add timeout, as nhooyr suggested 
  *https://github.com/kyeett/adventure/commit/dc4d19281a19b64a9cf2b2a2a91ee9381365229a#r48240148
```go
ctx, _ := context.WithTimeout(context.Background(), 5*time.Second)
c, _, err := websocket.Dial(ctx, u.String(), nil)
```
* In concurrent code, add locks (or channels or something) to avoid race conditions.
  * https://github.com/kyeett/adventure/commit/dc4d19281a19b64a9cf2b2a2a91ee9381365229a#r48240376

Hope this helps!
