### ISSUE TITLE
NetConn leaks timers

### ISSUE THREAD

**Issue by ash2k** [nhooyr/websocket#243]
Hey, first of all thanks a lot for `NetConn()`! I have written one myself, but then discovered this library and decided to use it instead.

I have noticed that `netConn.Close()` does not call `Stop()` on `writeTimer` and `readTimer`. I think it should at least if the deadlines have been set. Otherwise these timers are lingering around and that can be an issue if there are a lot of connections.

**Comment by nhooyr** [comment]
Great catch! Will fix soon.
