### ISSUE TITLE
Missleading origin error message

### ISSUE THREAD

**Issue by laliluna** [nhooyr/websocket#247]
When a proxy does not correctly set the origin, I found the error message is missleading.
 
I got 
`Accept failed: failed to accept WebSocket connection: request Origin "http://localhost:5555" is not authorized for Host "localhost:9000"`

so I introduced
`OriginPatterns: []string{"http://localhost:5555"},`

But the code is  expecting the origin without the trailling _http://_

The error message in _authenticateOrigin_  could use the value, it is actually checking, ie. u.Host instead of origin

`return fmt.Errorf("request Origin %q is not authorized for Host %q", origin, r.Host)`

Cheers Sebastian

**Comment by nhooyr** [comment]
Great catch!

The error message should be fixed to print just the host.
