### ISSUE TITLE
Re-use io buffers

### ISSUE THREAD

**Issue by andersfylling** [nhooyr/websocket#250]
I see I have the option to copy the content of a buffer into a buffer of my own. Ideally I would like to use a shared buffer between my code and this library, simply because I don't want multiple buffers and avoid copying.

Is this something you'd consider for this library?

**Comment by nhooyr** [comment]
I don't fully understand the suggestion. In terms of the API, what would you like exposed?

**Comment by andersfylling** [comment]
I'm browsing through the code and I wonder about the byte slice allocation for reads, right now I only see the pool use for writes:

https://github.com/nhooyr/websocket/blob/2c44f2822e4cbc71dc7503e0427c76b394636539/ws_js.go#L304

But I assume you are initializing byte slices on need when you get a incoming packet?
I would essentially like an exported pool interface, where i can inject my own pool.

**Comment by nhooyr** [comment]
So in general, reads are zero alloc. Only allocation is the byte slice you provide.

As for writes, the only thing allocated is the Writer which iirc is 8 bytes. You provide the byte slice so the library doesn't allocate anything.

The file you linked is for Wasm.

For the entire connection's lifespan we use a `*bufio.Reader` and a `*bufio.Writer` which are by default pooled and sized at 4 KB.

As far as I understand, there really isn't a good reason to want to inject your own. You don't gain any real performance advantage as the library's already doing its own pooling. gorilla exposing it directly was a mistake in its API.

i.e net/http and doesn't expose a pooling interface but instead lets you adjust the transport's buffer size and with https://github.com/golang/go/issues/13870 will let you adjust the server's buffer size.

**Comment by nhooyr** [comment]
Lmk if you have any more questions @andersfylling!
