### ISSUE TITLE
Error should not be returned on non-zero http client timeout

### ISSUE THREAD

**Issue by swithek** [nhooyr/websocket#260]
Having a warning about non-zero http client timeout is useful, but it should be a documentation-level warning not an actual error. With the current implementation it's not possible to use the same http client for both standard http requests and websocket events, even when a context with timeout is provided during dialing.

Related to: #67

**Comment by nhooyr** [comment]
Hi @swithek 

I guess we can copy the http client, remove the timeout and use that instead.

Would that work for your use case?

The reason it errors out is that a timeout on the client causes response bodies to not be writable, and so we can't use it for the WebSocket protocol.

**Comment by swithek** [comment]
Thank you for your swift response.

Yes, copying the client would work. Would this be an internal change or should this be done before passing it as an option? Having it as an internal feature would be a bit more convenient when working on multiple projects.
