### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by deansheather** [nhooyr/websocket#262]
No releases since May? WTF?!?

**Comment by ammario** [comment]
Scandalous

**Comment by dpastoor** [comment]
I'm not sure if this is trolling - the repo clearly shows activity even 14 days ago and merged pull requests a week ago https://github.com/nhooyr/websocket/pull/261

**Comment by fuskovic** [comment]
nah

> I'm not sure if this is trolling - the repo clearly shows activity even 14 days ago and merged pull requests a week ago #261
> 
> edit: i see that you all are part of the cdr org as well and likely this is in gest. Happened to come across my feed and given the amount of toxicity around hacktober fest and general open source pushiness I felt obliged to comment

nah bro

**Comment by nhooyr** [comment]
@dpastoor Yea sorry about this. These boys got carried away during yesterday's game night.
