### ISSUE TITLE
Non-CloseError, non-sentinel error on EOF 

### ISSUE THREAD

**Issue by cameronelliott** [nhooyr/websocket#263]
First, before I launch into my issue, let me say, thanks for writing nhooyr/websocket, I see  some things I really love, like the support for contexts on the reads and writes, and lots of other great decisions!

Anyway...

I got a  stack trace as included below, where the bold text of the error is from nhooyr/websocket, and the non-bold part preceding the bold is from my code.
Basically what happened, is an EOF occurred on a read, which is nothing unusual in production.

But, what I am surprised about, is that a non-sentinel type error was returned for the EOF on read.
(A type of 'error', rather than a chain containing 'CloseError')
[What are sentinel errors](https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully)

I kind of was hoping to get an error chain where 'CloseError' was included on any EOF conditions.

(like maybe this EOF could be converted to CloseError.StatusGoingAway or something similar.)

So, I am wondering if you think getting to the point where all EOFs possible return a sentinel-error 
is a good idea, or not really?

Thanks,
Cameron

F1013 20:16:12.719740    1448 main.go:234] err or read() or write() 192.168.86.1:39038: **failed to get reader: failed to read frame header: EOF**
goroutine 44 [running]:
github.com/golang/glog.stacks(0xc00007b500, 0xc0003ce0a0, 0x8f, 0x9d)
	/home/c/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:769 +0xb9
github.com/golang/glog.(*loggingT).output(0xb60640, 0xc000000003, 0xc000142620, 0xb02a1a, 0x7, 0xea, 0x0)
	/home/c/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:720 +0x39a
github.com/golang/glog.(*loggingT).printf(0xb60640, 0x3, 0x8a171e, 0x1f, 0xc00057f9d8, 0x2, 0x2)
	/home/c/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:655 +0x153
github.com/golang/glog.Fatalf(...)
	/home/c/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:1148
main.handleSource(0x920160, 0xc0000c4380, 0xc0000b6900)
	/home/c/back2back/main.go:234 +0x58c
net/http.HandlerFunc.ServeHTTP(0x8b6448, 0x920160, 0xc0000c4380, 0xc0000b6900)
	/usr/local/go/src/net/http/server.go:2042 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001580c0, 0x920160, 0xc0000c4380, 0xc0000b6700)
	/home/c/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
net/http.serverHandler.ServeHTTP(0xc000176380, 0x920160, 0xc0000c4380, 0xc0000b6700)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0001d0320, 0x920d60, 0xc000098f00)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c
exit status 255

**Comment by nhooyr** [comment]
Hi @cameronelliott!

First, thanks for the kind words!

So according to the WebSocket spec, we shouldn't be doing any such conversion. Instead, we can return `StatusAbnormalClosure` as browsers do when a connection randomly terminates but I decided it'd be better to return the full Go error but now I'm not entirely sure. I can see how this is confusing.

I'll keep this issue open and think on it for the next release.

**Comment by cameronelliott** [comment]
I'm sorry, I am a bit new to Go errors and the new 1.13 error stuff also,
it looks like maybe all I need to do is check for EOF with this:
if errors.Is(err, io.EOF) { 
//blah
}

and then I can detect EOF on both the read and write calls without needing to worry about digging through error strings looking for EOF, and without the library needing to convert every EOF condition to a sentinel value like I mentioned.

Does that sound about right?

**Comment by cameronelliott** [comment]
I suppose that I am curious if that is how you personally would write production code with this package?

So this is the post-read and post-write general error handling I am basically looking at using:
(return is exiting from a read-loop basically)

```go
if err != nil {
			if errors.Is(err,io.EOF) {
				glog.Infof("EOF on %v: %v", r.RemoteAddr, err)
                                return
			}
			x := websocket.CloseStatus(err)

			if x == websocket.StatusNormalClosure || x == websocket.StatusGoingAway {
				return
			}
			if websocket.CloseStatus(err) != -1 {
				glog.Warningf("unexpected close err %v: %v", r.RemoteAddr, err)
				return
			}
			glog.Fatalf("err on read() or write() %v: %v", r.RemoteAddr, err)
		}
```

**Comment by cameronelliott** [comment]
I'm sorry, I hope you don't feel I wasted your time with this.
Shall I close this issue?

**Comment by cameronelliott** [comment]
I am not sure why RSC proposed using fmt.Errorf() to wrap errors,
[in errd.Wrap](https://github.com/golang/go/issues/32676)
rather than errors.Wrap(), but it seems problematic from
the perspective of easily identifying io.EOF errors,
as the usage of fmt.Errorf() doesn't use an error chain, and
thus requires receivers of errors to parse strings rather
than use `if errors.Is(err, io.EOF) {` to detect closed
socket conditions.

If we were to use errors.Wrap() rather than fmt.Errorf(),
it may simplify io.EOF handling, and thus creating
robust websocket servers.

Are you open to discussing the pros and cons of this?


P.S.
This article by the author of pkg/errors, explains the
downsides of using fmt.Errorf() vs errors.Wrap()
[Dave Cheney Talk/Post *Don’t just check errors, handle them gracefully* 2016](https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully)
> Even something as well meaning as using fmt.Errorf to add some context to the error will defeat the caller’s equality test. Instead the caller will be forced to look at the output of the error‘s Error method to see if it matches a specific string.

**Comment by cameronelliott** [comment]
Actually, I noticed something interesting.
errors.Wrap is used [Here](https://github.com/nhooyr/websocket/blob/2c44f2822e4cbc71dc7503e0427c76b394636539/close_notjs.go#L35)

But, fmt.Errorf is used [Here](https://github.com/nhooyr/websocket/blob/master/internal/errd/wrap.go#L12)


I wonder if there is a logic between the different usages or, like much of my code, it just kinda is what seemed to make sense at this time??

**Comment by cameronelliott** [comment]
One last thought, a comparison of the code to check & parse io.EOF 
based upon fmt.Errorf vs errors.Wrap

```go
func nhooyrWebsocketError(err error, identifier string) error {
	if err != nil {
		// current method to check for wrapped io.EOF
		// easy to get wrong
		if strings.HasSuffix(err.Error()," EOF"){
			glog.Infof("EOF on %v: %v", identifier, err)
			return nil
		}
```

```go
func nhooyrWebsocketError(err error, identifier string) error {
	if err != nil {


		// errors.Wrap approach ro check for wrapped io.EOF
	        if errors.Is(err, io.EOF) {
		 	glog.Infof("EOF on %v: %v", identifier, err)
		 	return nil
		}
```

**Comment by nhooyr** [comment]
Np, glad you figured things out!

I was just visiting family the last few days so didn't have time to respond.
