### ISSUE TITLE
conn.Write(context.Background(), websocket.MessageBinary, p)=> invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by daimengxiaozhi** [nhooyr/websocket#264]
print conn is this:
&{ <nil> false <nil> 0 <nil> <nil> <nil> <nil> <nil> [0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] <nil> <nil> <nil> <nil> [] [0 0 0 0 0 0 0 0] {false false false false 0 0 false 0} <nil> {0 0} <nil> false 0 {0 0} map[]}
how to solve this problem

**Comment by nhooyr** [comment]
Please post the full stack trace.

**Comment by daimengxiaozhi** [comment]
> Please post the full stack trace.

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7eb226]

goroutine 21 [running]:
nhooyr.io/websocket.(*msgWriterState).reset(0x0, 0x9c22e0, 0xc000022068, 0x2, 0xc0006e5d30, 0x47b7bc)
        /Users/apple/go/pkg/mod/nhooyr.io/websocket@v1.8.6/write.go:142 +0x26
nhooyr.io/websocket.(*Conn).writer(0xc000072820, 0x9c22e0, 0xc000022068, 0x2, 0x8f8da0, 0xc0000680d0, 0xc0006e5dc0, 0x4d6077)
        /Users/apple/go/pkg/mod/nhooyr.io/websocket@v1.8.6/write.go:111 +0x54
nhooyr.io/websocket.(*Conn).write(0xc000072820, 0x9c22e0, 0xc000022068, 0x2, 0xc000aed080, 0x54, 0x54, 0x0, 0x0, 0x0)
        /Users/apple/go/pkg/mod/nhooyr.io/websocket@v1.8.6/write.go:122 +0x8b
nhooyr.io/websocket.(*Conn).Write(0xc000072820, 0x9c22e0, 0xc000022068, 0x2, 0xc000aed080, 0x54, 0x54, 0x0, 0x1)
        /Users/apple/go/pkg/mod/nhooyr.io/websocket@v1.8.6/write.go:42 +0x7a
xxx/server.handleTun(0xc00009a000, 0xc0006ea000, 0x34, 0x1000)
        /Users/apple/Documents/projects/go/xxx/server/tun.go:69 +0x605
xxx/server.(*Server).readTun(0xc00009a000)
        /Users/apple/Documents/projects/go/xxx/server/tun.go:21 +0x121
created by xxx/server.RunServer
        /Users/apple/Documents/projects/go/xxx/server/server.go:18 +0xef`

**Comment by nhooyr** [comment]
Can you share some of the source?

**Comment by daimengxiaozhi** [comment]
nhooyr.io/websocket v1.8.6
the final error location is => err := mw.mu.lock(ctx)   
 
func (mw *msgWriterState) reset(ctx context.Context, typ MessageType) error {
	err := mw.mu.lock(ctx)
	if err != nil {
		return err
	}

	mw.ctx = ctx
	mw.opcode = opcode(typ)
	mw.flate = false

	mw.trimWriter.reset()

	return nil
}

**Comment by daimengxiaozhi** [comment]
Can I improvise a solution to this problem. Determine if conn is an exception.

**Comment by nhooyr** [comment]
Sorry, I meant I'd like see your source!

**Comment by daimengxiaozhi** [comment]
> Sorry, I meant I'd like see your source!

Sorry, the source can't give you, because it's a company project.  Can you open an interface to determine if the CONN is valid.

**Comment by nhooyr** [comment]
> Can you open an interface to determine if the CONN is valid.

I don't know what you mean by that.

As far as I can tell, there's no bug in the library. The stack trace indicates you're using a nil `*Conn`. That's the only way it's possible.

Without the source I can't help you spot the bug in your code.

**Comment by daimengxiaozhi** [comment]
Thank you!  *Con I judge not nil so I don't know how to deal with this problem anymore.   I don't know why that is!
