### ISSUE TITLE
Help with usage

### ISSUE THREAD

**Issue by wzhsh90** [nhooyr/websocket#268]
how can I use it with gin framework

is there an example ?

**Comment by wzhsh90** [comment]
Error during WebSocket handshake: Unexpected response code: 200

**Comment by nhooyr** [comment]
https://github.com/nhooyr/websocket/blob/c9f314abd11b749d43bb61fd214171f8bb4e4173/conn_test.go#L497

Should just work if you pass in `ginCtx.Writer` and `ginCtx.Request` to `Upgrade`.

Also make sure you're using the latest version of this library as Gin compatibility has been broken in the past. #180

**Comment by wzhsh90** [comment]
conn, err := websocket.Accept(ctx.Writer, ctx.Request, nil)
	if err == nil {
		go func() {
			for {
				var msg models.WsReceiveModel
				err := wsjson.Read(ctx, conn, &msg)
				if err == nil {
					//todo analyze the data
				} else {
					config.LoggerErr("页面可能断开啦", err)
					//todo close websocket
					break
				}

			}
		}()
	}

that is my code , i want to listener the close event , how can i to listen the close event.


if I use github.com/gorilla/websocket, when i leave my page , the read will trill err ， but nhooyr.io/websocket will not trigger .

**Comment by nhooyr** [comment]
Hmm, the read should error when you leave the page. The browser will send a close frame which will cause the read to error out.

There are quite a few tests for this behaviour so I don't believe it's a bug in the library.

Can you provide a standalone example I can test?

**Comment by wzhsh90** [comment]
i find the problem . the log not print on ide console . It write into the file.

**Comment by nhooyr** [comment]
Awesome!
