### ISSUE TITLE
Detecting when client connection is gone away between calls to Read/Write/Ping

### ISSUE THREAD

**Issue by mpobrien** [nhooyr/websocket#270]
I'm trying to understand how (or if it is even possible) to detect that a websocket client has disconnected from the server, to trigger and propagate context cancelation, without explicitly having to make calls to `Read()` or `Ping()`. 
My first instinct was to use `r.Context()`, but it appears that after the websocket connection is accepted, this context does not expire if the client disconnects.

In the below example, it appears that the `r.Context()` passed to `LongRunningOperation()` does not expire, even when the websocket client has disconnected. Ideally, it should be possible to interrupt that function using a context if the client goes away, but I can't figure out how.

```go
package main

import (
	"fmt"
	"net/http"

	"nhooyr.io/websocket"
)

func main() {
	http.HandleFunc("/", HelloServer)
	http.ListenAndServe(":8080", nil)
}

func HelloServer(w http.ResponseWriter, r *http.Request) {
	ws, wsErr := websocket.Accept(w, r, nil)
	if wsErr != nil {
		// handle error
	}

	for {
		msgType, msg, err := ws.Read(r.Context())
		if err != nil {
			// handle error
		}

		LongRunningOperation(r.Context(), msg, msgType)
	}
}
```

I welcome your thoughts!
Thanks.

**Comment by nhooyr** [comment]
Hi @mpobrien!

I believe you're looking for `CloseRead`. See the example here:

https://github.com/nhooyr/websocket/blob/c9f314abd11b749d43bb61fd214171f8bb4e4173/example_test.go#L82-L118

Best,
Anmol

**Comment by nhooyr** [comment]
Nevermind, I think I misread.

Unfortunately there's no way to do what you're looking for without running `Read` async (in a separate goroutine) to how you handle your messages. If you're not actively reading from the connection, you'll never be notified that it's disconnected.
