### ISSUE TITLE
Ability to drop out of net.Conn mode

### ISSUE THREAD

**Issue by jefferai** [nhooyr/websocket#271]
Hi there, and thanks so much for a wonderful library!

I had some old code that did something very similar to your net.Conn support before you added it, and I'd love to fully move over to your net.Conn mode (which is working well in other uses), but there's an issue -- I need to be able to close the net.Conn connection without closing the websocket connection itself. The reason is that I want to perform connection reuse -- that is, go into a raw net.Conn mode, drop out when some event occurs, and then send some (application-layer) status/coordination between two sides to figure out the next operation -- which may in fact be to go back into a net.Conn mode.

The reason I don't want to simply drop the connection and reconnect is that doing so will tear down state for the connection on the remote end, and it is expensive to build it back up (e.g. requires database reads and RPC communication).

My code is not super transferable here because I was working on top of the primitives from this library; more or less, it would chunk data as it came in within a deadline, pop that into a message with a predictable format that also included the type of message, e.g. carrying binary data, and send that over. Less efficient than what you have, for sure.

However, looking at the RFC, one way that you could enable this kind of "dropping out" of the net.Conn mode would be to offer an extension during negotiation (if enabled). This would enable the ability to put extension data in control frames. A Close operation on a net.Conn pulled out with dropout enabled would then send a frame with zero bytes of binary data but containing extension data indicating the mode switch, causing the other side to also drop back to normal behavior.

I'm happy to work on this, but want to ensure that it's (a) welcome and (b) that there is agreement on design.

Looking forward to feedback!

(Edit: clarifying that the status/coordination is application-level, not within this library)

**Comment by jefferai** [comment]
There's another way that might be simpler: since ping frames are allowed to send application data, a call on the local side to Close could set `eofed` (thus denying more reads locally, and this could also deny writes locally) and send a ping frame containing data that indicates that the remote side should drop from this mode. (The library doesn't currently allow application data to be sent in Ping, even though the RFC allows it, so it's unlikely to cause issues to use it for library signaling.)

One challenge might be draining frames that are a part of the netConn. This requires a contract that once the ping is sent, no more frames related to the connection are sent; similarly, once the pong is sent, the same holds true for the remote side. So this would require a bit more coordination and potentially locking to ensure that this contract is true. Mutexes would be relatively simple (a mutex for Read, a mutex for Write, both must be held by Close to send the ping, and `eofed` or something similar is set at this time to ensure no more reading/writing on the conn), plus a notification to the lib that it needs to ignore frames (except, potentially Close frames) until it receives that pong.

**Comment by nhooyr** [comment]
Hi @jefferai!

First, thanks for the kind words!

Unfortunately I wouldn't be comfortable with supporting a non standard extension in the core library. I think this should be easy to implement on top of the `NetConn` wrapper.

I'd embed it into a struct and then define `Read` to read the first 8 bytes into a `uint64` and if it's zero, then that means the remote end has closed the connection and you should start using `*websocket.Conn` again. If greater than zero, then that's the length of the next chunk. Finally, change `Write` to write the byte slice with the length prefixed, however if zero, then nothing should be written. Lastly, `Close` needs to just write a zero byte to the connection.

I have considered exposing more internals of the library so that extensions like the one you describe are easy to implement but I've been very busy recently so haven't had time to continue to iterate on this library.

**Comment by jefferai** [comment]
I did notice that a lot of PRs were merged by you fixing various bugs but no recent release...are you planning any release soon to get those fixes out there?

**Comment by nhooyr** [comment]
> I did notice that a lot of PRs were merged by you fixing various bugs but no recent release...are you planning any release soon to get those fixes out there?

Yes unfortunately that's true right now. My winter break is coming up next week, I'm planning on getting this repository up to shape then.

**Comment by jefferai** [comment]
Awesome, thanks!
