### ISSUE TITLE
compiling wasm

### ISSUE THREAD

**Issue by DAT4** [nhooyr/websocket#290]
Hi :-)

When I try to compile to wasm with
```
env GOOS=js GOARCH=wasm go build
```
I get this error:
```
./connection.go:27:77: unknown field 'HTTPHeader' in struct literal of type websocket.DialOptions
```
This is line 25, 26 and 27 in connection.go >> my code
```
header := http.Header{}
header.Add("Authorization", "bearer "+token)
c, _, err = websocket.Dial(context.Background(), u, &websocket.DialOptions{HTTPHeader: header})
```

When I compile normally with `go build` then everything works fine.

**Comment by nhooyr** [comment]
Sorry for the delayed response but you can't use HTTPHeader when compiling for Wasm. I believe there's a note in the docs.

It's just not supported by the javascript WebSocket API.
