### ISSUE TITLE
Read context expiring closes websocket

### ISSUE THREAD

**Issue by joaohaas** [nhooyr/websocket#294]
```go
ctx, _ := context.WithDeadline(mdm.ctx, time.Unix(0, 0))
_, _, err = ws.Read(ctx)  // failed to get reader: context deadline exceeded
_, _, err = ws.Read(context.Background())  // failed to get reader: WebSocket closed: read timed out: context deadline exceeded
```

From my understanding, the first context expiring is causing the websocket to close, which I believe is not correct. If it is. The same happens if you try to write after the first read, which is the use case I need (read until a timeout, and then send a message).

If this is the expected behaviour would be great to at least have it documented.

**Comment by joaohaas** [comment]
Probably is somehow related to this issue:
https://github.com/nhooyr/websocket/issues/289

**Comment by joaohaas** [comment]
Huh, just saw https://github.com/nhooyr/websocket/issues/242, shoul've checked closed tickets before.

Really unfortunate, I really like using contexts for stuff.

Closing this.

**Comment by nhooyr** [comment]
Yea sorry it's documented in the dev branch but that hasn't made it to master yet. #256
