### ISSUE TITLE
Subproctol() return empty string

### ISSUE THREAD

**Issue by shaozi** [nhooyr/websocket#296]
Hi,

The following simple code get empty string as subprotocol:

```go
	ws, err := websocket.Accept(w, r, nil)
	subp := ws.Subprotocol()
	log.Printf("Subprotocol = %s\n", subp)
```

Javascript:
```javascript
new WebSocket("ws://localhost:8080/ws", "sub")
```

**Comment by nhooyr** [comment]
Hello @shaozi!

You need to include the protocol in the accept options in order for subprotocol negotiation to take place.

Otherwise `Accept` doesn't know which protocols are supported and will reject the subprotocol `"sub"` from the client.

https://pkg.go.dev/nhooyr.io/websocket#AcceptOptions

🍻

**Comment by nhooyr** [comment]
And apologies for the delayed response!

**Comment by shaozi** [comment]
Ok will give it a try
