### ISSUE TITLE
Remove third party test dependencies

### ISSUE THREAD

**Issue by yinzara** [nhooyr/websocket#297]
The github.com/gin-gonic/gin dependency has a http response splitting vulnerability in versions less than 1.7.0:
https://github.com/gin-gonic/gin/pull/2632

Upgrading the dependency to 1.7.0 or higher will fix this vulnerability (current version is 1.7.1)

**Comment by nhooyr** [comment]
Hi @yinzara we don't actually use gin anywhere other than in tests but I'll be sure to do this in the next release.

**Comment by nhooyr** [comment]
And apologies for the delayed response.

**Comment by jmichalak-fluxninja** [comment]
@nhooyr Any update on this? Github alerts me with https://github.com/advisories/GHSA-h395-qcrw-5vmq

**Comment by nhooyr** [comment]
> https://gophers.slack.com/archives/C9BMAAFFB/p1691163449401899

@prochac can you copy and paste the contents of the link? I'm not a member of the Gophers Slack.

**Comment by nhooyr** [comment]
Done in dev.
