### ISSUE TITLE
Make errAlreadyWroteClose exported

### ISSUE THREAD

**Issue by Antonboom** [nhooyr/websocket#300]
Hello!

I would like to get a mechanism to avoid unnecessary logging of the closing error:
```golang
	defer func() {
		err2 := wsConn.Close(websocket.StatusInternalError, "the sky is falling")
		if err2 != nil {
			logger.WithError(err2).Error("error on close websocket")
		}
	}()
```

Thanks.

**Comment by emersion** [comment]
Related: https://github.com/nhooyr/websocket/issues/286

**Comment by nhooyr** [comment]
Thanks for reporting @Antonboom.

Yes as @emersion pointed out please follow #286 as the tracking issue for this.

And apologies for the delayed response!
