### ISSUE TITLE
I want to migrate gorilla/websocket to this library, need some guide.

### ISSUE THREAD

**Issue by cnmade** [nhooyr/websocket#309]
I want to migrate gorilla/websocket to this library, need some guide.

Need some help to know how to migrate it. 

Any document or tech guide to let us read ?
thanks.

**Comment by nhooyr** [comment]
Hello @cnmade 

Unfortunately not as of yet but there is some work in progress at https://github.com/nhooyr/websocket/issues/217

Please follow along there.

And apologies for the delayed response.
