### ISSUE TITLE
wspb.go uses deprecated protobuf package

### ISSUE THREAD

**Issue by iamcalledrob** [nhooyr/websocket#311]
I love the idea of the protobuf helpers in wspb.go, but when trying to use them I noticed that wspb.go imports `github.com/golang/protobuf/proto`. Since this module is deprecated, this helper can't easily be used in a codebase using the newer protobuf library (`google.golang.org/protobuf`).

From https://github.com/golang/protobuf:
> It has been superseded by the google.golang.org/protobuf module, which contains an updated and simplified API, support for protobuf reflection, and many other improvements. We recommend that new code use the google.golang.org/protobuf module.

It would be wonderful if this import could be switched out to use the newer module 😀

**Comment by nhooyr** [comment]
Oh very nice! Will definitely do in the next major release as it would be a breaking change.

Though perhaps this also suggests protobuf helpers don't belong in the core package and should be published elsewhere?

**Comment by ash2k** [comment]
Yes, moving the helpers out e.g. into an example that can be copied or into a separate module would be good to avoid transitive dependencies.

**Comment by nhooyr** [comment]
Done in dev.

**Comment by xornet-sl** [comment]
Is this a joke? Why wspb - a public package got removed?!
Guys, you exposed this, people use it, it is NOT an internal package. Why you just brake everything in PATCH release??!!
I even can not re-create the functionality of wspb as it uses `internal` package. Why you did that? Was it really a problem just to update the needed dependencies and let it live?
