### ISSUE TITLE
Option to disable message read limit completely

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [nhooyr/websocket#322]
I do not want to limit the size of possible messages. Currently, the only way to do this is to set the read limit to a very high number. Would  it be possible to add an option to completely disable the limit?

**Comment by gnvk** [comment]
@nhooyr Can you please share your thoughts on this one?

**Comment by nhooyr** [comment]
Sounds good, will make `-1` do this.

**Comment by gnvk** [comment]
Great, thanks! Looking forward to it.

**Comment by nhooyr** [comment]
Done in dev.
