### ISSUE TITLE
net.Conn: Return real addresses

### ISSUE THREAD

**Issue by edisonwsk** [nhooyr/websocket#327]
How to get LocalAddr or RemoteAddr?now returns “websocket/unknown-addr ”

**Comment by nhooyr** [comment]
Right now it's hardcoded as `websocket/unknown-addr` but I suppose I could make it return the real addresses.

Related https://github.com/nhooyr/websocket/issues/331

**Comment by nhooyr** [comment]
Dealt with in #299

To the current extent possible anyway. See PR for the caveat.
