### ISSUE TITLE
Redirects to `wss://...` don't work

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [nhooyr/websocket#333]
If the server responds with `302 https://test.com/ws` the redirect works, but if the response is `302 wss://test.com/ws` the redirect fails with ` failed to WebSocket dial: failed to send handshake request: Get "wss://test.com/ws": unsupported protocol scheme "wss"`

I was able to fix the issue by specifying a custom `http.Client` in the `DialOptions`
```golang
HTTPClient: &http.Client{
	CheckRedirect: func(req *http.Request, via []*http.Request) error {
		switch req.URL.Scheme {
		case "ws":
			req.URL.Scheme = "http"
		case "wss":
			req.URL.Scheme = "https"
		case "http", "https":
		default:
			return fmt.Errorf("unexpected url scheme: %q", req.URL.Scheme)
		}
		return nil
	},
},
```

Do you think this should be included in the default client? I would be happy to open a PR with the functionality,

**Comment by nhooyr** [comment]
Hmm interesting. I'm not sure what browsers do here. Do they accept both? If so, we should too.

**Comment by SoMuchForSubtlety** [comment]
From the WebSocket spec[^1]

> Once the client's opening handshake has been sent, the client MUST
>    wait for a response from the server before sending any further data.
>    The client MUST validate the server's response as follows:
> 
>    1.  If the status code received from the server is not 101, the
>        client handles the response per HTTP [[RFC2616](https://www.rfc-editor.org/rfc/rfc2616)] procedures.  In
>        particular, the client might perform authentication if it
>        receives a 401 status code; **the server might redirect the client
>        using a 3xx status code** (but clients are not required to follow
>        them), etc.  Otherwise, proceed as follows.

[^1]: https://www.rfc-editor.org/rfc/rfc6455

**Comment by nhooyr** [comment]
I don't see how that clarifies the issue at hand? It doesn't speak on whether the redirect URL should use `http` or `https`.

**Comment by nhooyr** [comment]
Sorry I mean `wss` or `https`.

**Comment by nhooyr** [comment]
I'll make it work anyway.

**Comment by nhooyr** [comment]
Done in dev but still needs a test.

**Comment by nhooyr** [comment]
Done.
