### ISSUE TITLE
document http client must use context timeout and not timeout on struct

### ISSUE THREAD

**Issue by yihexi** [nhooyr/websocket#341]
when I set  http.DefaultClient.Timeout = time.Second * 10, websocket.Dial will get an error "failed to WebSocket dial: response body is not a io.ReadWriteCloser: *http.cancelTimerBody"

verson: nhooyr.io/websocket v1.8.7

this is because in the dial.go line 128:	rwc, ok := respBody.(io.ReadWriteCloser), it convert respBody to an io.ReadWriteCloser, I think it should be rwc, ok := respBody.(io.ReadCloser). 

in general, respBody is a *http.readWriteCloserBody, but if http.DefaultClient.Timeout is set, it will be a *http.cancelTimerBody, which is just an io.ReadCloser.

**Comment by nhooyr** [comment]
Ah right, I'll document this.

**Comment by mateusfmello** [comment]
@nhooyr 

Was this implemented in the project?

I'm having the same problem here.

**Comment by nhooyr** [comment]
Nothing to implement, just an unfortunate quirk of `*http.Client`. Please use the context to pass in a timeout.

**Comment by mateusfmello** [comment]
Looking at the readme example, I switched to `context.WithTimeout`, but the error continues

**Comment by nhooyr** [comment]
Ah right yea so I'll change the code here to remove the Timeout from `*http.Client` but right now you have to make sure Timeout is `0` on whatever `*http.Client` you use with `websocket.Dial`.

**Comment by mateusfmello** [comment]
I believe that nothing needs to be done, as `context.WithCancel(context.Background())` works perfectly too, I believe the problem in my code is something else, I'm rewriting it.

The bug occurred after closing the connection and reopening

**Comment by nhooyr** [comment]
Oh interesting, I'll definitely test to make sure.

**Comment by nhooyr** [comment]
Fixed in dev.
