### ISSUE TITLE
http://nhooyr.io is down; unable to fetch module

### ISSUE THREAD

**Issue by bojdell** [nhooyr/websocket#348]
```
go: nhooyr.io/websocket@v1.8.7: unrecognized import path "nhooyr.io/websocket": https fetch: Get "https://nhooyr.io/websocket?go-get=1": dial tcp: lookup nhooyr.io: no such host
go: downloading nhooyr.io/websocket v1.8.7
```

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3486165/194188546-8d9fa8b8-0831-445c-84ca-4715fdc5d426.png">

**Comment by nhooyr** [comment]
Can you still reproduce this?

**Comment by nhooyr** [comment]
https://nhooyr.io/websocket seems to work for me.

**Comment by geekgonecrazy** [comment]
Ran into this same issue today:

I had to add the following to my go.mod

```
replace noohyr.io/websocket => github.com/noohyr/websocket v1.8.7
```

That seemed to mitigate the issue.

**Comment by nhooyr** [comment]
Related https://github.com/nhooyr/websocket/issues/372

I moved my hosting to GCP, hopefully that fixes this.
