### ISSUE TITLE
add nocopy to conn

### ISSUE THREAD

**Issue by piegamesde** [nhooyr/websocket#349]
Stack trace:

```
go.ts:72 panic: runtime error: index out of range [0] with length 0
go.ts:72 
go.ts:72 goroutine 15 [running]:
go.ts:72 nhooyr.io/websocket.(*Conn).read(0x4b8000, 0xa1238, 0x438b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
go.ts:72 	/root/go/pkg/mod/nhooyr.io/websocket@v1.8.7/ws_js.go:132 +0x35
go.ts:72 nhooyr.io/websocket.(*Conn).Read(0x4b8000, 0xa1238, 0x438b00, 0x0, 0x2a0108, 0x18, 0x9eed8, 0x1b920004, 0x4b8000)
go.ts:72 	/root/go/pkg/mod/nhooyr.io/websocket@v1.8.7/ws_js.go:107 +0xb
```

At the time where the panic happens, the message that is about to be read has already been received by the browser.

I looked at [the relevant code](https://github.com/nhooyr/websocket/blob/master/ws_js.go#L132) and it looks a bit weird at first but could not find any obvious bug causing this.

**Comment by piegamesde** [comment]
Semi-related: If I understand the code correctly, it is using a single-element channel and a buffer plus mutex in order to create an unbounded channel. This means that no backpressure will be applied to the sender if the receiver is not fast enough at processing the messages. I think this should be changed.

**Comment by piegamesde** [comment]
It turns out that we were storing the `Conn` struct by value, which caused some issues with Mutexes getting copied. Switching to pointers trivially fixed the issue: https://github.com/LeastAuthority/wormhole-william/pull/91/files

However, are there any ways to ensure this does not happen again? Can we somehow make sure that `Conn` is copy-safe, or alternatively that it is not copied accidentally? At the very least, I think this should be documented.

**Comment by nhooyr** [comment]
> However, are there any ways to ensure this does not happen again? Can we somehow make sure that Conn is copy-safe, or alternatively that it is not copied accidentally? At the very least, I think this should be documented.

`go vet` should have flagged this for you. Or perhaps I need to add something here to make it do so.

It is already documented, that's why the receiver on all Conn methods is a pointer and why a pointer is returned. You can't go from pointer -> value and expect things to work.

Yup I'll add https://github.com/golang/go/issues/8005#issuecomment-190753527

**Comment by nhooyr** [comment]
Fixed in dev.
