### ISSUE TITLE
failed to WebSocket dial: unsupported permessage-deflate parameter: "server_max_window_bits=15" 

### ISSUE THREAD

**Issue by 1770697081** [nhooyr/websocket#351]
I use this lib connect binance，2022.10.18 find this question。And then insert some code then can Bypass the problem。
dial.go ->verifyServerExtensions() 
```go
	for _, p := range ext.params {
		switch p {
		case "client_no_context_takeover":
			copts.clientNoContextTakeover = true
			continue
		case "server_no_context_takeover":
			copts.serverNoContextTakeover = true
			continue
		}
                //add code
		if strings.HasPrefix(p, "server_max_window_bits") {
			fmt.Println("server_max_window_bits:", p)
			continue
		}
		return nil, fmt.Errorf("unsupported permessage-deflate parameter: %q", p)
	}
```
        我在使用此包连接binance币安时，最近出现标题的错误，然后我尝试在websocket包的dial.go文件的verifyServerExtensions()函数中添加了兼容server_max_window_bits字段的代码，然后就能使用了。我看文档这字段功能好像是压缩之类的功能，不确定是否后续会出现新问题.
       抱歉，英文太菜了。

**Comment by faof** [comment]
我直接注释了这个，跑起来没问题

**Comment by 1770697081** [comment]
不确定以后服务器更新后，会不会导致客户端无法使用。可能现在服务端只是回复了此字段，但是没有实际使用这个内容。

**Comment by guotie** [comment]
same problem.

**Comment by guotie** [comment]
seem nobody maintains this repo?

**Comment by LiYisen** [comment]
same problem.

**Comment by LiYisen** [comment]
> @guotie Don't expect maintainers to respond this fast lol they not paid
> 
> Just disable compression. Should work.

how to disable compression

**Comment by kunsonx** [comment]
Check on this library: https://github.com/crypto-zero/go-binance

**Comment by felbit** [comment]
Disabling compression did it for me, thanks @nightwolfz!

I have had the issue on client side and had to set [CompressionMode in the DailOptions](https://pkg.go.dev/nhooyr.io/websocket#DialOptions):

```go
conn, _, err := websocket.Dial(ctx, ADDR, &websocket.DialOptions{
	CompressionMode: websocket.CompressionDisabled,
})
```

**Comment by nhooyr** [comment]
Going to just disable compression by default.

**Comment by nhooyr** [comment]
Disabled by default in #256

**Comment by nhooyr** [comment]
Perhaps in regards to this specific issue, I should allow server_max_window_bits=15 and client_max_window_bits=15 as that's the default window size.

**Comment by nhooyr** [comment]
Dev should work now with binance out of the box though. Let me know if it doesn't. v1.8.8 is soon to be released.

**Comment by nhooyr** [comment]
Ah looks like the fix is here already: https://github.com/nhooyr/websocket/pull/258

**Comment by nhooyr** [comment]
Done with #258
