### ISSUE TITLE
Avoid returning `0, nil` in netConn.Read

### ISSUE THREAD

**Issue by MarcoPolo** [nhooyr/websocket#367]
When we reach the end of the frame we currently return `0, nil` (https://github.com/nhooyr/websocket/blob/master/netconn.go#L118). The `io.Reader` docs discourage this:

> Implementations of Read are discouraged from returning a zero byte count with a nil error, except when len(p) == 0.

This seems to have confused other folks as well: https://github.com/nhooyr/websocket/issues/353

My recommendation is we don't return 0, nil and instead block until we get data or a proper error.

**Comment by nhooyr** [comment]
Will change because the docs for io.Reader discourage it but if your code is using `io.Reader` correctly this should never be a problem.

**Comment by MarcoPolo** [comment]
How do you think you want to solve it? Loop until error or data? Or something else?

I'm happy to submit a patch.

**Comment by nhooyr** [comment]
Related https://github.com/golang/go/issues/27531#issuecomment-764061206

**Comment by nhooyr** [comment]
Fixed in dev.
