### ISSUE TITLE
Move from `io/ioutil` as it is deprecated

### ISSUE THREAD

**Issue by keystroke3** [nhooyr/websocket#370]
`io/ioutil` is now deprecated but is still being used here:

```zsh
❯ rg 'ioutil\.' .
./read.go
41:	b, err := ioutil.ReadAll(r)

./dial_test.go
78:					Body: ioutil.NopCloser(strings.NewReader("hi")),
100:				Body:       ioutil.NopCloser(strings.NewReader("hi")),

./dial.go
117:			b, _ := ioutil.ReadAll(r)
119:			resp.Body = ioutil.NopCloser(bytes.NewReader(b))

./examples/chat/chat.go
101:	msg, err := ioutil.ReadAll(body)

./conn_test.go
177:		b, err := ioutil.ReadAll(n1)
208:		_, err := ioutil.ReadAll(n1)

./autobahn_test.go
149:	b, err := ioutil.ReadAll(r)
164:	wstestOut, err := ioutil.ReadFile(path)
209:	f, err := ioutil.TempFile("", "temp.json")```

**Comment by Jacalz** [comment]
FYI: This only makes sense if you want to raise the minimum supported Go version to 1.16 (from 1.13).

I don’t personally have anything against it but it is worth noting.

**Comment by nhooyr** [comment]
Yup the minimum go version will be raised soon as part of #359

**Comment by sagarishere** [comment]
why is this still open when this has been done now.

**Comment by nhooyr** [comment]
I don't believe this has been done?

**Comment by keystroke3** [comment]
I believe it is done, unless there is something else that is blocking the merge.

**Comment by nhooyr** [comment]
Right, there's a PR but just hasn't been merged.

**Comment by keystroke3** [comment]
Closing because the PR has been merged.
