### ISSUE TITLE
Vanity URL behaving inconsistently based on geolocation

### ISSUE THREAD

**Issue by pojntfx** [nhooyr/websocket#372]
After some of my builds in GH actions started failing last night with the following error:

```plaintext
a3ce@1677509870 hydrapp-example-forms/pkg/frontend/server.go:15:2: nhooyr.io/websocket@v1.8.7: unrecognized import path "nhooyr.io/websocket": parse https://nhooyr.io/websocket?go-get=1: no go-import meta tags (meta tag github.com/nhooyr/websocket did not match import path nhooyr.io/websocket)
```

I decided to investigate and found out that the vanity URL is giving different, incompatible results based on the clients geolocation. For example, when requesting from Frankfurt, Germany, its correctly returning the meta tag (`<meta name="go-import" content="nhooyr.io/websocket git https://github.com/nhooyr/websocket" />`):

![Screenshot from 2023-02-27 16-54-42](https://user-images.githubusercontent.com/28832235/221613896-eba5d1d6-c3fb-4d28-b26e-9f3d22c8adf6.png)

Whereas requests from US-East get redirected instead, resulting in a failed build:

![Screenshot from 2023-02-27 16-54-05](https://user-images.githubusercontent.com/28832235/221614131-a085a257-f4eb-408f-88f1-0815760e5945.png)

Requests from US-West can't connect to the vanity URL at all:

![image](https://user-images.githubusercontent.com/28832235/221614235-2c36ec77-6eeb-4212-9d5b-2a727f474a07.png)

Is there some kind of maintenance going on or might this be a bug in the server?

**Comment by nhooyr** [comment]
Super weird no idea. My site is just hosted on netlify. https://www.netlify.com/

I just triggered a redeploy, hopefully that fixes it.

**Comment by pojntfx** [comment]
Thanks for the quick response; I'm not sure why its not working yet, the builds are still failing, but I'm guessing its probably due to Netlify doing something strange in the background

**Comment by nhooyr** [comment]
I'll switch my hosting from netlify sometime soon.

**Comment by robertvolkmann** [comment]
@pojntfx Try to use the official golang proxy with GOPROXY="https://proxy.golang.org,direct"

@nhooyr You could reproduce it with GOPROXY=direct go get -v nhooyr.io/websocket

I encounter the issue by using the go binary packaged by the Fedora project because it doesn't use the golang proxy by default.

**Comment by pojntfx** [comment]
@robertvolkmann Neat, that did explain why it happened in my instance in particular (this is as part of an RPM-based Go build system after all)! Here is the commit that fixed it from occuring in this particular configuration: https://github.com/pojntfx/hydrapp/commit/d49c91290bd69e6392b4c91d21bc1ce5fec7c3dc

**Comment by nhooyr** [comment]
```
$ GOPROXY=direct go get -v nhooyr.io/websocket
get "nhooyr.io/websocket": found meta tag vcs.metaImport{Prefix:"nhooyr.io/websocket", VCS:"git", RepoRoot:"https://github.com/nhooyr/websocket"} at //nhooyr.io/websocket?go-get=1
go: added github.com/klauspost/compress v1.10.3
go: added nhooyr.io/websocket v1.8.7
```

Worked fine for me. I'm in BC by the US border with Idaho.

**Comment by nhooyr** [comment]
Once I switch hosting, hopefully it just goes away.

**Comment by robbierolin** [comment]
I'm seeing this from hosts in US-EAST and GOPROXY="https://proxy.golang.org" is not an option for me currently. Is there anything you can do to fix this?

**Comment by nhooyr** [comment]
I'll switch to a GCP bucket tonight.

**Comment by nhooyr** [comment]
I switched it over to a GCP bucket, it may take some time to take effect. Please let me know if you guys are still able to reproduce the bizarre connectivity issues in a day or two.

**Comment by nhooyr** [comment]
Going to close for now, will reopen if there are further issues.
