### ISSUE TITLE
Typo in description on the pkg.go.dev

### ISSUE THREAD

**Issue by streamdp** [nhooyr/websocket#376]
Hi! I found little typo in description on the  https://pkg.go.dev/nhooyr.io/websocket#example-package-CrossOrigin
`OriginPatterns: []str"example.com"}ing{,`
should be  `OriginPatterns: []string{"example.com"},`

![Screenshot_20230305_203958](https://user-images.githubusercontent.com/59509850/222976688-edc490e9-d340-4829-86c4-069c96d0a221.png)

**Comment by nhooyr** [comment]
<img width="775" alt="Screenshot 2023-03-05 at 10 04 43 AM" src="https://user-images.githubusercontent.com/10180857/222977746-d80af77c-1834-47e8-a1c4-f716fa209175.png">

Hello! I think that was an intermittent glitch somehow, it appears correct now.
