### ISSUE TITLE
Enabling/disabling TCP_NODELAY

### ISSUE THREAD

**Issue by cedws** [nhooyr/websocket#383]
TCP sockets in Go have the `TCP_NODELAY` socket option set by default. This disables Nagle's algorithm which intends to reduce tinygrams by introducing small delays and aggregating them together into larger TCP packets.

This is appropriate for applications running in datacenters with low latency/low jitter network connections, but for an application connecting to an Internet service from a laptop, it's not so good.

https://withinboredom.info/blog/2022/12/29/golang-is-evil-on-shitty-networks/

You can call `SetNoDelay(bool)` on `net.TCPConn` to configure the `TCP_NODELAY` option. Since this library uses `net/http`, I'm sure there's a way to call this on the underlying connection, but I couldn't see how from having a brief look. I'll post any findings here.

**Comment by nhooyr** [comment]
Write a custom `net.Listener`.

**Comment by cedws** [comment]
Is it desirable to expose a method for this? Lot of consumers probably want Nagle's off.

**Comment by lesismal** [comment]
I set it by `http.Server.ConnState`:
https://github.com/lesismal/go-websocket-benchmark/blob/main/frameworks/nhooyr/server.go#L61

But really think it's not convenient.

**Comment by nhooyr** [comment]
> Is it desirable to expose a method for this? Lot of consumers probably want Nagle's off.

Right but why should my library expose a method when you can already do this at a deeper level by passing a custom net.Listener to http.Server or ConnState like @lesismal suggested.

Maybe in the future it'll be possible simply as a result of me allowing direct access to the *net.Conn, see #331

**Comment by waldner** [comment]
While setting TCP_NODELAY can be done on the server side (although with some work, as shown), it seems to me that there's no way to do that on the client side (ie, what you get from `websocket.Dial`). Am I wrong?
