### ISSUE TITLE
Typo in `Reader` documentation

### ISSUE THREAD

**Issue by mr-aboutin** [nhooyr/websocket#386]
# Issue

Documentation for func `(c *Conn) Reader` in (`read.go`) reads: 
```
Reader reads from the connection until until there is a WebSocket
```

# Fix

Remove the duplicate `until`

**Comment by nhooyr** [comment]
Fixed in [4d349b2](https://github.com/nhooyr/websocket/pull/256/commits/4d349b2629f3e9a5de7a8da29665ee2e5cd48f70)
