### ISSUE TITLE
Why not use Conn.Read directly in netConn.Read  ?

### ISSUE THREAD

**Issue by cyj19** [nhooyr/websocket#387]
Hello nhooyr!  I have a question. Why not use Conn.Read directly in netConn.Read  ? 
This reduces handling of cases where n == 0 returned by io.Reader.

The example is as follows:
```
func (c *netConn) Read(p []byte) (int, error) {
	c.readMu.Lock()
	defer c.readMu.Unlock()

	if c.eofed {
		return 0, io.EOF
	}
       
       // use Conn.Read method
	typ, data, err := c.c.Read(c.readContext)
	if err != nil {
		switch CloseStatus(err) {
		case StatusNormalClosure, StatusGoingAway:
			c.eofed = true
			return 0, io.EOF
		}
		return 0, err
	}
         if typ != c.msgType {
		err := fmt.Errorf("unexpected frame type read (expected %v): %v", c.msgType, typ)
		c.c.Close(StatusUnsupportedData, err.Error())
		return 0, err
	 }
	
       // copy the actual data to p	
        n := copy(p, data)
	return n, nil
}
```

Looking forward to your answer, thanks!

**Comment by nhooyr** [comment]
First performance. With Read, you're penalized by the allocation of the body slice. With Reader, you reuse whatever the caller passed in. Second, you'd have to keep the data slice around between calls like you keep the reader so it wouldn't be much less complex. Your example would cause data loss if len(p) < len(data)

Hope that clarifies and sorry for the delay.
