### ISSUE TITLE
I found gin-gonic and gorilla/websocket in dependency list?

### ISSUE THREAD

**Issue by casatwy** [nhooyr/websocket#388]
running `go mod graph` in my project and I found that `gin-gonic` and `gorilla/websocket` is in `nhooyr/websocket`'s dependency list.

![1](https://user-images.githubusercontent.com/1005781/233815951-2d219924-91b4-4815-a90b-97dae358bb9e.png)

and gorilla/websocket?

![233815994-8c55eebb-137d-4f77-9ac2-f4827b8f08b6](https://user-images.githubusercontent.com/1005781/233816102-d14ab9ca-27ce-4955-9474-56d9b5d1d25c.png)

**Comment by casatwy** [comment]
and gorilla/websocket ?

![截屏2023-04-23 10 19 59](https://user-images.githubusercontent.com/1005781/233815994-8c55eebb-137d-4f77-9ac2-f4827b8f08b6.png)

**Comment by nhooyr** [comment]
See #297
