### ISSUE TITLE
The WebSocket protocol stipulates that the payload data of the close frame cannot exceed 123 bytes.

### ISSUE THREAD

**Issue by wrenchonline** [nhooyr/websocket#389]
```golang
...
err := wsjson.Read(ctx, c, &v)
	if err != nil {
		logger.Warning(err.Error())
		break
	}
...
```

```golang
err = wsjson.Write(ctx, info.Conn, Msg ) // Msg > 123
```

The reason for this problem is that the WebSocket protocol stipulates that the payload data of the close frame cannot exceed 123 bytes. If the payload exceeds 123 bytes, the above error will occur.

The wsjson.Write function does not seem to be checked and sent in pieces

**Comment by nhooyr** [comment]
Not sure what you're referring to here? You haven't sent a close frame in either snippets of your code?
