### ISSUE TITLE
Any update?

### ISSUE THREAD

**Issue by Hoodie-Kang** [nhooyr/websocket#392]
No updates nowadays :(
 What's in progress? Is there any update plan?

**Comment by KunalSin9h** [comment]
is this project is not actively maintained? , @nhooyr

**Comment by merlindru** [comment]
In the readme it says a bit more about the status of the project:

```
note: I haven't been responsive for questions/reports on the issue tracker but I do read through and there are no outstanding bugs. There are certainly some nice to haves that I should merge in/figure out but nothing critical. I haven't given up on adding new features and cleaning up the code further, just been busy. Should anything critical arise, I will fix it.
```

So you could consider it "complete" -- bugs will be fixed, but no new features for now

**Comment by nhooyr** [comment]
Been busy but back on it full time till EOY. See #402 and #256
