### ISSUE TITLE
How to connect behind a proxy

### ISSUE THREAD

**Issue by LCozzoli** [nhooyr/websocket#395]
Hey, 
I'm currently using gorilla and wanted to migrate to this more recent library, unfortunately I can't seems to find any info about a proxy support. Is there a way to connect to a websocket server using an http proxy like gorilla does ?

**Comment by nhooyr** [comment]
Yup, pass in an http.Client configured for your proxy. See DialOptions and net/http docs on proxy configuration for http.Client.

**Comment by LCozzoli** [comment]
Perfect, thanks!

**Comment by LCozzoli** [comment]
I'm running into `Connection header "keep-alive" does not contain Upgrade` issues when connecting 

`wsURL := "ws://example.com" // replace with your websocket server URL
	proxyURL := "http://proxy_host:proxy_port"  // replace with your proxy server URL

	proxyURLParsed, err := url.Parse(proxyURL)
	if err != nil {
		log.Fatalf("Failed to parse proxy URL: %v", err)
	}

	dialer := &websocket.DialOptions{
		HTTPClient: &http.Client{
			Transport: &http.Transport{
				Proxy: http.ProxyURL(proxyURLParsed),
			},
		},
	}

	conn, _, err := websocket.Dial(context.Background(), wsURL, dialer)
	if err != nil {
		log.Fatalf("Failed to connect: %v", err)
	}`

**Comment by nhooyr** [comment]
Not sure what you mean by header "keep-alive"? What's the full error message and on what line are you getting it?

**Comment by LCozzoli** [comment]
Hello, 
I think that my request is getting blocked by this line:
https://github.com/nhooyr/websocket/blob/14fb98eba64eeb5e9d06a88b98c47ae924ac82b4/accept.go#LL165C56-L165C56
I get 
`Failed to connect: WebSocket protocol violation: Connection header "keep-alive" does not contain Upgrade`

**Comment by nhooyr** [comment]
What version of Go are you using?

**Comment by LCozzoli** [comment]
`go version go1.20.2 windows/amd64`
The proxy I used to try works with Gorilla, I tried the same code (the closest syntax).

**Comment by LCozzoli** [comment]
https://i.gyazo.com/15d98fb63abf45f73ecea6b6b57ac447.png
https://i.gyazo.com/73185f1b44da57ed748fa9c2b89f2907.png

**Comment by nhooyr** [comment]
All good, I'll setup a full go test case as I'll want to ensure this works going forward.

**Comment by nhooyr** [comment]
Yup, test passes so not sure what you were dealing with. Are you sure your forward proxy is/was working correctly? Was it working with Gorilla?

Closing for now, feel free to comment if you have further information.
