### ISSUE TITLE
Delay in Ping Pong

### ISSUE THREAD

**Issue by satya-devloper** [nhooyr/websocket#396]
Currently my server is sending 10000 msg in 3min in one grouting and also regular ping interval is happening on 15 second in second gorouting. Although  msg I m able to send  all on websocket but when I check the time taken to ping in log, what I can see that it takes around 30s and sometimes more that one min to complete ping request to server.
But when I m not sending any data only ping is going then it takes millescond to complete ping.
Just want to clarify my doubt why it's taking time to ping in first case. Is there any framework related bottlenecks or something else.

Also my server is not able to process all the request , with the rate which client is sending and I m seeing msg loss in server side i.e out of 10000 msg seeing only around 5000 recieved in server side log.

Just want to clarify my doubts , is it something related to framework, or network congestion or memory issue?

**Comment by nhooyr** [comment]
See https://go.dev/blog/pprof

If you write the code and can reproduce across multiple machines, feel free to reopen and I'll look into it.
