### ISSUE TITLE
How to capture EOF error?

### ISSUE THREAD

**Issue by parthokr** [nhooyr/websocket#398]
`wsjson` doesn't return any error that matches with io.EOF.
Then how to detect if a client disconnects?

**Comment by bilinxing** [comment]
Same question. Also a question, is this program still being maintained? Or should I still turn to [gorilla](https://github.com/gorilla/websocket)

**Comment by parthokr** [comment]
@bilinxing switching back to gorilla seems to be promising now as they unarchived their repos 🎉

**Comment by nhooyr** [comment]
See #402 re maintenance.

As for your question, see https://pkg.go.dev/nhooyr.io/websocket#CloseError

**Comment by nhooyr** [comment]
Also opened #406 to document this better. The documentation of my library just isn't good enough which is why these kinds of issues keep coming up. I need better examples that demonstrate how to use the library with perfect correctness.
