### ISSUE TITLE
failed to get reader: received close frame: status = StatusNormalClosure and reason = "" 

### ISSUE THREAD

**Issue by maggie44** [nhooyr/websocket#403]
I have tried an implementation that uses a subscribe and unsubscribe through one websocket:

https://github.com/maggie44/websocket-subscribe

It seems whatever I try I always get an error when the user disconnects, although a sort of non-error error then reports to the console that it closed ok. I can't seem to close the reader gracefully without this error:

```
failed to get reader: received close frame: status = StatusNormalClosure and reason = "" 
```

Any ideas on how to achieve this?

**Comment by nhooyr** [comment]
Yup, use https://pkg.go.dev/nhooyr.io/websocket#CloseStatus to check that it's a normal closure and if so, ignore the error.

See the godoc example.
