### ISSUE TITLE
Provide the ability to convert io.ReadWriteCloser to websocket

### ISSUE THREAD

**Issue by baixudong007** [nhooyr/websocket#404]
## The following code is implemented by me using go: linkname, and I think you can provide an interface to make it work natively
```go

type compressionOptions struct {
	clientNoContextTakeover bool
	serverNoContextTakeover bool
}
type connConfig struct {
	subprotocol    string
	rwc            io.ReadWriteCloser
	client         bool
	copts          *compressionOptions
	flateThreshold int

	br *bufio.Reader
	bw *bufio.Writer
}

//go:linkname newConn nhooyr.io/websocket.newConn
func newConn(cfg connConfig) *websocket.Conn

//go:linkname getBufioReader nhooyr.io/websocket.getBufioReader
func getBufioReader(r io.Reader) *bufio.Reader

//go:linkname getBufioWriter nhooyr.io/websocket.getBufioWriter
func getBufioWriter(w io.Writer) *bufio.Writer

type Conn struct {
	rwc    io.ReadWriteCloser
	conn   *websocket.Conn
	option Option
}
type Option struct {
	Subprotocols         []string        // Subprotocols lists the WebSocket subprotocols to negotiate with the server.
	CompressionMode      CompressionMode // CompressionMode controls the compression mode.
	CompressionThreshold int             // CompressionThreshold controls the minimum size of a message before compression is applied ,Defaults to 512 bytes for CompressionNoContextTakeover and 128 bytes for CompressionContextTakeover.
	CompressionOptions   *compressionOptions
}

func NewConn(conn io.ReadWriteCloser, isClient bool, option Option) *Conn {
	var subprotocol string
	if len(option.Subprotocols) > 0 {
		subprotocol = option.Subprotocols[0]
	}
	return &Conn{
		rwc:    conn,
		option: option,
		conn: newConn(connConfig{
			subprotocol:    subprotocol,
			rwc:            conn,
			client:         isClient,
			copts:          option.CompressionOptions,
			flateThreshold: option.CompressionThreshold,
			br:             getBufioReader(conn),
			bw:             getBufioWriter(conn),
		}),
	}
}
```

**Comment by nhooyr** [comment]
Can you clarify the purpose? Are you wanting to speak websockets over an arbitrary pipe? If so why?

**Comment by baixudong007** [comment]
> Can you clarify the purpose? Are you wanting to speak websockets over an arbitrary pipe? If so why?

I am implementing a request library and I need to implement the websocket function for it. If I use websocket. Dial to implement this function, as websocket.Dial has already helped us with HTTP requests, it will result in many functions that cannot be fully customized. For example, I want to add ja3 and proxy functions to websocket and seamlessly integrate with existing systems.
In the future, I will also implement a packet grabbing function similar to Fillder, which requires intermediate interception of connections. These all force me to abandon websocket.Dial, I need a deeper level of ability to convert io.ReadWriteCloser into websockets, so that it can better integrate with other systems.

**Comment by nhooyr** [comment]
Understood. Can you write a http.RoundTripper to return your io.ReadWriteCloser as r.Body? That should work if you pass a `*http.Client` with your `http.RoundTripper` into websocket.Dial
See the dial.go code for how the library performs the handshake and casts r.Body into r.ReadWriteCloser.

Going to close, feel free to reopen and comment if that doesn't resolve your issue.

**Comment by baixudong007** [comment]
> Understood. Can you write a http.RoundTripper to return your io.ReadWriteCloser as r.Body? That should work if you pass a `*http.Client` with your `http.RoundTripper` into websocket.Dial See the dial.go code for how the library performs the handshake and casts r.Body into r.ReadWriteCloser.
> 
> Going to close, feel free to reopen and comment if that doesn't resolve your issue.

The newConn function is currently in an undisclosed state. Do you have any plans to publicly disclose this function? Simply disclosing this function can solve all the above problems. What I need is to be able to control the part of the HTTP protocol on my own, rather than you doing it, so that I have more freedom and can do more things

**Comment by nhooyr** [comment]
Right but you can already do that by hooking into the `http.RoundTripper` that's passed into `websocket.Dial` instead of me exposing additional API. Just have your round tripper ignore the handshake request from the library and do whatever you need to do to get the io.ReadWriteCloser and return it from there.

I'd like to avoid exposing API that isn't strictly necessary.
