### ISSUE TITLE
Our apps break using the package >= v1.8.8

### ISSUE THREAD

**Issue by oderwat** [nhooyr/websocket#410]
Hi @nhooyr,

we just spent some hours searching an error in our application which resulted from the "patch" update from v1.8.7 to v.1.8.8. Besides the problem (which is of unclear origin by now), I wonder a bit that two years of development get releases as a patch increase.

Anyway. With the new code we get "read limited at -1 bytes" in the upstream error message. The code we use seems not to be too sophisticated, but we have a hard time to debug what is going wrong.

Gladly we have some public demonstration code that exposes the same problem:

https://github.com/oderwat/go-nats-app/

If one changes the `nhooyr.io/websocket` from v1.8.7 to v1.8.9 (or v1.8.8) the connection returns the same error.

Because of the massive amount of changes we would really like if you could check out what may go wrong here, as you likely remember what change may introduce the problem on our (or your) side.

Related code is most likely [here](https://github.com/oderwat/go-nats-app/blob/master/front/natsclient.go)

**Comment by nhooyr** [comment]
Yea def should have upped the minor instead of a patch but welp. It wasn't really two years of development though more like a few weeks of mainly bug fixes, just was super delayed.

Looking into it.

**Comment by nhooyr** [comment]
Not sure how that error is even possible. `-1` means this code should run instead: https://github.com/nhooyr/websocket/blob/b4e4f4f12ee47d9827cee352c52b612944bad6bf/read.go#L485

Thus never entering this branch here which is where your error is coming from https://github.com/nhooyr/websocket/blob/b4e4f4f12ee47d9827cee352c52b612944bad6bf/read.go#L489

**Comment by nhooyr** [comment]
Oh this is in WASM!

**Comment by nhooyr** [comment]
Pushed a fix to dev https://github.com/nhooyr/websocket/commit/454aee86997aeb75f06c6cecbc15c3355b5e8d30

Can you try to confirm it fixes the issue? If it does, I'll make a v1.8.10 release.

**Comment by oderwat** [comment]
I can confirm that the change fixes it.

**Comment by nhooyr** [comment]
Sweet, will release now.

**Comment by oderwat** [comment]
It does not yet find the release. I guess that is because the "nhooyr.io/websocket" repository is not yet synced?

**Comment by oderwat** [comment]
Yeah, that thing drove me nuts in the past already. TY for the headsup.
