### ISSUE TITLE
Not Getting Pong Response on Time

### ISSUE THREAD

**Issue by satya-devloper** [nhooyr/websocket#413]
Currently I m sending the ping from client every 15 seconds, but getting error after some time **failed to ping: WebSocket closed: failed to read frame header:** 
Although it seems I m doing as per the suggestion of documentation 
Just want to know what are the possible scenarios where I can miss pong response from server. Although as per the documentation library used to handle pong automatically.

**Client Code** :
---------------------------------------

```
func start() {
   go wc.writeMessages(writeCtx, writeWaitgroup)
   go wc.readMessages()
}

func (wc *WebCommunicator) writeMessages(writeCtx context.Context, writeWaitgroup *sync.WaitGroup) {
for {
    // pinging at each 15 second here
}

func (wc *WebCommunicator) readMessages() {
    for {
		select {
		case <-wc.done:
			return
		default:
			wc.readMessageFromConn()
		}
	}
}

func (wc *WebCommunicator) eadMessageFromConn() {

	p, buf, err := cAdapter.ReadChannel(wc)
	if err != nil {
	        fmt.Println("READ ERROR",
		cAdapter.RetryConnect(wc)
		return
	}
}

```

**Server Code** 
------------------------
reading this in infinite for loop
```
func read(ctx context.Context, c *websocket.Conn) (err error) {
	c.SetReadLimit(config.ReadLimit)
	err = wsjson.Read(ctx, c, &v)
        if err != nil {
	  return err
       }
}
```

**Comment by nhooyr** [comment]
What's the full error you're getting?

**Comment by satya-devloper** [comment]
> What's the full error you're getting?

failed to ping: WebSocket closed: failed to read frame header: read tcp 112.11.110.200:43562->104.106.108.103:443: read: connection timed out"

**Comment by nhooyr** [comment]
And this error is occurring on the client? What error does the server give for the same connection?

**Comment by satya-devloper** [comment]
> And this error is occurring on the client? What error does the server give for the same connection?

failed to get reader: failed to read frame header: EOF

**Comment by satya-devloper** [comment]
Just to add more detail : I am handling 5000 ws connection on a server and there is a loadbalancer in between client and server

**Comment by satya-devloper** [comment]
@nhooyr , let me know if you need any information

**Comment by nhooyr** [comment]
Doesn't seem related to the library to me. Looks like the TCP read is timing out. Maybe increase your OS level tcp read timeout.

Feel free to comment with further info if you disagree.

**Comment by nhooyr** [comment]
Although you are saying you're pinging every 15s... So I'm not really sure. I'd need a reproducible example to debug. I can't think of any reason why this would happen.
