### ISSUE TITLE
dead example in readme: CloseNow 

### ISSUE THREAD

**Issue by alixander** [nhooyr/websocket#416]
This example does not work. `CloseNow()` is not a method

https://github.com/nhooyr/websocket#client

**Comment by nhooyr** [comment]
Was added in the latest release, please upgrade.

https://github.com/nhooyr/websocket/releases/tag/v1.8.8
> https://github.com/nhooyr/websocket/commit/a94999fb3a308b562b13c85f4d458564adea9147 API Add CloseNow https://github.com/nhooyr/websocket/issues/384
