### ISSUE TITLE
discussion: strange API for the common use case

### ISSUE THREAD

**Issue by mitar** [nhooyr/websocket#419]
I am just starting exploring this library and I must say I am a bit surprised by its API. The `Conn`'s `Read` returns message by message, that is fine. But `Reader` is strange to me. I would assume that the common use case is that whole connection is used for the same message type. Or you are sending JSONs or proto bufs, but you are generally not mixing them? Or if you do, you mix them at the sub-protocol level. But having mixed message types inside same sub-protocol, that is strange to me.

So my ideal API would be that in `Accept` I provide expected sub-protocol to be used and expected message type. Then after connection is established, I can call `Reader` (or the connection struct itself is reader/writer) where every `Read` on that reader gives me next message in full (maybe this buffering feature could be another option). All ping/pong messages and other internal wiring is not exposed to me. I just want messages themselves. Then I can use that reader and just read from it. Or pass it to `json.Decoder` and I get structs one by one out in a loop. No need for `wsjson`. If an unexpected message type arrives, `Read` on the reader returns an error.

**Comment by lxzan** [comment]
In fact, []byte or io.Reader is essential, and the serialization method depends on the application developer.

**Comment by nhooyr** [comment]
Interesting. I suppose yes I could have implemented it like that but I could see scenarios where you do want to switch from text to binary messages for performance reasons. Like transferring binary assets in a game. The current API is most flexible and though I try not to optimize for that, in this case I think it's warranted.

Regarding everything else you're saying it's trivial to wrap `*websocket.Conn` in a type specific to your needs and provide whatever methods you want for reading and writing messages without being exposed to the rest of the API.
