### ISSUE TITLE
Can't activate CORS for examples /chat/   

### ISSUE THREAD

**Issue by remotejob** [nhooyr/websocket#430]
`func (cs *chatServer) ServeHTTP(w http.ResponseWriter, r *http.Request) {`
`w.Header().Add("Access-Control-Allow-Origin", "*"`
	
Don't work for me, any help appreciated.

**Comment by nhooyr** [comment]
Can you clarify what doesn't work?

**Comment by nhooyr** [comment]
Going to close, feel free to reopen if there's additional information.
