### ISSUE TITLE
Error: panic: unaligned 64-bit atomic operation on arm32-bit while establishing websocket connection

### ISSUE THREAD

**Issue by Himani-relan** [nhooyr/websocket#432]
Hi,
I have upgraded the library version to v1.8.8 and running it on my arm32 machine. While trying to establish a websocket connection it fails with this error : ` panic: unaligned 64-bit atomic operation`
Full logs below:
`panic: unaligned 64-bit atomic operation
goroutine 38 [running]:
2024-01-23T08:13:24.341158+00:00 4Z6RWM3-idrac 1121111e190f42c48e78746625c64444[4429]: runtime/internal/atomic.panicUnaligned()
#011/usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Load64(0xeae34c)
#011/usr/local/go/src/runtime/internal/atomic/atomic_arm.s:280 +0x14
nhooyr.io/websocket.(*netConn).read(0xeae320, {0xe58000, 0x1000, 0x1000})`

I am guessing this particular PR changed the code: https://github.com/nhooyr/websocket/commit/0a61ffe87a498f8ff9fef8020bee799cfa4f927f?diff=split&w=0 

I had to make it work by changing the data type of readExpired and writeExpired to int32 & LoadInt64 and StoreInt64 function into LoadInt32 and StoreInt32 respectively in this module: https://github.com/nhooyr/websocket/blob/master/netconn.go

**Comment by nhooyr** [comment]
Ah darn, good catch will fix.

**Comment by nhooyr** [comment]
Fixed by https://github.com/nhooyr/websocket/pull/438
