### ISSUE TITLE
Goroutine spike when closing connections in v1.8.10 (regression)

### ISSUE THREAD

**Issue by ash2k** [nhooyr/websocket#434]
When we bumped the library from `v1.8.7` to `v1.8.10` we started seeing huge memory usage spikes when the process is shutting down. It turned out to be because the library starts lots of goroutines in some (?) case.

Blue graph is RAM usage in percentage of max allowed. Note how spikes start at some point - that's when the version with the library update was rolled out.
![Screenshot_2023-12-14_at_9 32 10_pm](https://github.com/nhooyr/websocket/assets/126021/4e97b6d8-6757-48da-a43f-cd4b21ce64a2)

Screenshot from Google Profiler with the width of the flame graph showing the proportion of goroutines with a certain stacktrace. Note that at the moment of capture there was 153,983 goroutines, most of them from the library.

<img width="1895" alt="Screenshot_2024-02-13_at_7 13 48_am" src="https://github.com/nhooyr/websocket/assets/126021/8a4fbb6e-316d-4a7c-8c0e-55a681e3d746">

This is a regression. Code worked fine until the version bump and works fine again since we downgraded the library.

Original issue: https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent/-/issues/492

**Comment by nhooyr** [comment]
Related #429

Terrible code here  on my part, will need to rewrite the close code to fix. Will try and do soon.

**Comment by nhooyr** [comment]
Thanks for reporting. I've fixed this in #427. Please review and let me know if you see anything else.

**Comment by nhooyr** [comment]
Sorry for the delay. Fixed by #427.
