### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by AntonioSun** [nhooyr/websocket#453]
Thanks for providing such idiomatic Go pkg first of all. How compatible of the clients / servers built by [websocket](https://github.com/nhooyr/websocket) are?

The https://github.com/vi/websocat is a popular command-line client for WebSockets, like netcat (or curl) for ws:// with advanced socat-like functions. I can use it out of the box. however, 

 For the clients / servers built by [websocket](https://github.com/nhooyr/websocket), I'm having difficulties for other tools to use it. 

- clients built by [websocket](https://github.com/nhooyr/websocket) can access some public websocket servers, but it cannot access the websocket we build [our own](https://github.com/XRPLF/clio), yet `websocat` accesses both just fine.
- servers built by [websocket](https://github.com/nhooyr/websocket) can only be accessed by clients built by [websocket](https://github.com/nhooyr/websocket), not `websocat`, nor my k6 test scripts.

Please advice how I can build it with maximum compatibility. thx.

**Comment by nhooyr** [comment]
Hi @AntonioSun thanks for the kind words.

Can you clarify what you mean when you say the library cannot access your own WebSocket server? What kind of error are you seeing?

**Comment by AntonioSun** [comment]
By "our own WebSocket server" I meant that the WebSocket server our company built ourselves, not using nhooyr/websocket, but C++. 

The error that I got from our server is, `Failed to receive message: failed to read JSON message: failed to unmarshal JSON: json: cannot unmarshal object into Go value of type string`

`tcpdump` reveals that it's a communication protocol problem, mostly even started on send part:

![image](https://github.com/nhooyr/websocket/assets/2840074/7c9a59ba-c1f6-4fe2-b376-ff811b0a46b6)

**Comment by nhooyr** [comment]
Can you test if the same occurs with gorilla/websocket?

**Comment by nhooyr** [comment]
And what error do you get from websocat?

**Comment by AntonioSun** [comment]
> And what error do you get from websocat?

```
$ echo '{ "id": 1, "command": "server_info" }' | websocat $WS_URL
2024/06/04 22:16:59 Received: map[command:server_info id:1]
2024/06/04 22:16:59 Echoed: map[command:server_info id:1]
{"command":"server_info","id":1}
2024/06/04 22:16:59 Failed to read message: failed to read JSON message: failed to get reader: received close frame: status = StatusNoStatusRcvd and reason = ""
```

I run the server and websocat on the same terminal, and it turns out that _websocat on itself is fine_, when running on other terminals. The `failed to read JSON message` is from my go code, will update where it comes from ...

**Comment by AntonioSun** [comment]
And, servers built by [websocket](https://github.com/nhooyr/websocket) work with my k6 test scripts now as well, after I've come back home and does not need to rush through things.

My bad before. Feel free to close it if you want, although I believe the client problem does exist, as shown in my previous screenshot.

**Comment by AntonioSun** [comment]
Oh, I found out what went wrong at work 

```go
	// Create a server
	addr = ":8080"
	server := &http.Server{
		Addr: addr,
	}
```

I use `addr = ":8080"` so as to listen on the local net, yet it only works for localhost, which I tested in my home, not over local net, which I tested at work. 

The `addr = ":8080"` form works for http server, what's the correct way here, to listen on the local net please?

**Comment by AntonioSun** [comment]
Oh, sorry for so many messages, this is not my normal style, just today I need to rush through so many things, 😭😭

So, in summary, putting pending issues at a single place,

- the client communication protocol problem
- the `failed to read JSON message` problem, which comes from the above `wsjson.Read`
- and how for server to listen on the local net

thanks

**Comment by nhooyr** [comment]
Use `localhost:8080` to listen only locally. `:8080` means to listen on all available interfaces.

I don't understand the other issues you're reporting. Can you try and reproduce using a small piece of code that I can try myself? My intuition is there's likely some user error here as you don't seem very experienced in network programming. Which is fine but then means I can't help you debug without a reproducible example.

**Comment by AntonioSun** [comment]
Ok, 

Let's first start with the official demo echo server:

> This directory contains a echo server example using nhooyr.io/websocket.
> 
> $ cd examples/echo
> $ go run . localhost:0
> listening on ws://127.0.0.1:51055
> 
> You can use a WebSocket client like https://github.com/hashrocket/ws to connect. 

```
$ go run . :51055
listening on ws://[::]:51055
```

Then from the client side:

```sh
$ ws ws://172.x.0.y:51055/
websocket: close 1008 (policy violation): client must speak the echo subprotocol

$ echo '{ "id": 1, "command": "server_info" }' | websocat -n1 ws://172.x.0.y:51055/ | wc
      0       0       0
```

So, seems that the official demo echo server does not work for either `ws` or `websocat` _out of the box_. 
Would you fix that please (doing the plain reply-as-is without using the echo subprotocol)? That would surely answer all my above questions. 

thanks

**Comment by nhooyr** [comment]
Remove the sub-protocols field from the accept config in the demo server and try that to see if it works.

**Comment by nhooyr** [comment]
And remove this: https://github.com/nhooyr/websocket/blob/master/internal/examples/echo/server.go#L33

Or maybe there's a way to pass in the subprotocol to `ws`? Maybe a flag.

**Comment by AntonioSun** [comment]
That works! Thanks!!

I'll close this one, and for the remaining client communication protocol problem, I'll open another if necessary.

**Comment by nhooyr** [comment]
Cheers!
