### ISSUE TITLE
Document how to have a separate idle and read timeout

### ISSUE THREAD

**Issue by nhooyr** [nhooyr/websocket#87]
```go
func read(ctx context.Context, c *websocket.Conn) ([]byte, error) {
	ctx, cancel := context.WithTimeout(ctx, time.Minute*30)
	defer cancel()

	_, r, err := c.Reader(ctx)
	if err != nil {
		return nil, err
	}

	// One minute max to read the received message.
	time.AfterFunc(time.Minute, cancel)

	return ioutil.ReadAll(r)
}
```

That code should be good in an example under Reader.

Related #86

**Comment by nhooyr** [comment]
If enough people need this, I can add a method to the conn `c.SetReadTimeout` that controls the maximum time spent reading each message. Then the context passed in would effectively act as the idle timeout.

**Comment by mikestead** [comment]
@nhooyr thanks for all the work on this library. Add me as a vote for this option 👍

**Comment by nhooyr** [comment]
> @nhooyr thanks for all the work on this library. Add me as a vote for this option

Thanks :)

> Specifically it currently looks like I'd have to unwrap the logic encapsulated in wsjson.Read if I wanted to have that functionality with this option. Let me know if not.

Yes, unfortunately you would need to unwrap the logic in wsjson. For now, I would recommend going that route as no one else has requested this option.

Is there a reason you can't just bound the entire wsjson read to something like a few minutes? As long as you have a read limit, things should be fine.

**Comment by mikestead** [comment]
No problem.

It was with the aim to have checks over the two different steps. A general longer term read wait timeout and a specific timeout once we actually have something to read.

**Comment by nhooyr** [comment]
Looks like this was lost somehow, will need to investigate why it isn't in master anymore.
