### ISSUE TITLE
Add function to error on any data messages from the peer

### ISSUE THREAD

**Issue by nhooyr** [nhooyr/websocket#98]
https://github.com/nhooyr/websocket/blob/31492255de53f0499a7255b5c4f45b345cb3ec7b/example_test.go#L77

@ammario suggested I add a function for that. I agree but I don't know what to name it.

**Comment by ammario** [comment]
CloseRead

**Comment by nhooyr** [comment]
That makes a lot of sense yup. Will add.

**Comment by nhooyr** [comment]
Nvm, if you call CloseRead, how will you cancel your context when the connection dies?

**Comment by nhooyr** [comment]
The function I'm thinking of is just

```go
func SomeName(ctx) {
    c.Reader(ctx)
    c.Close(websocket.StatusPolicyViolation, "server doesn't accept data messages")
}
```

So you'd use it like

```go
go func() {
    defer cancel()
    c.SomeName()
}()
```

**Comment by nhooyr** [comment]
I guess you could have:

```go
func (c *Conn) CloseRead(ctx context.Context) (context.Context) {
    // spawn goroutine in example and return a context that will be cancelled when the goroutine returns
}
```

That seems reasonable. 🤔
